/* Generated by tools/gen_ingenic_padmux.py -- do not edit.
 *
 * The four device functions of each pad. Ingenic selects between them
 * with one bit each in the port's INT, MSK, PAT1 and PAT0 registers
 * rather than with a field, so these are names and nothing else:
 * src/hal/ingenic_padmux.c holds the registers.
 *
 * Regenerate with:
 *   tools/gen_ingenic_padmux.py --soc T31 --spec T31_H.3_gpio_spec.pdf --soc T21 --spec platform.h --soc T23 --spec platform.h
 */

#ifndef HAL_INGENIC_PADMUX_H
#define HAL_INGENIC_PADMUX_H

#include "hal/ingenic_padmux_types.h"

/* T31: 77 pads named, of 96 in the SoC's 3 ports. A pad no source
 * names is not here at all, which is a different answer from one
 * whose four functions are all unused.
 *
 * From the GPIO spec's port summary tables: FUNCTION0..3 per
 * pad, named per wire.
 *   bb1d41a16f9809da  T31_H.3_gpio_spec.pdf
 */
static const ingenic_pad_t T31_pads[] = {
    {6, "PA06", {"SD0", "DVP_D6", "UART1_TXD", "reserved"}},
    {7, "PA07", {"SD1", "DVP_D7", "UART1_RXD", "reserved"}},
    {8, "PA08", {"SD2", "DVP_D8", "UART2_CTS", "MSC1_D0"}},
    {9, "PA09", {"SD3", "DVP_D9", "UART2_RTS", "MSC1_D1"}},
    {10, "PA10", {"SD4", "DVP_D10", "UART2_TXD", "MSC1_D2"}},
    {11, "PA11", {"SD5", "DVP_D11", "UART2_RXD", "MSC1_D3"}},
    {12, "PA12", {"SD6", "SMB0_SDA", "reserved", "reserved"}},
    {13, "PA13", {"SD7", "SMB0_SCK", "reserved", "reserved"}},
    {14, "PA14", {"SA0", "DVP_PCLK", "PWM0", "reserved"}},
    {15, "PA15", {"SA1", "DVP_MCLK", "reserved", "reserved"}},
    {16, "PA16", {"CS2", "DVP_HSYNC", "SMB1_SDA", "MSC1_CLK"}},
    {17, "PA17", {"RD", "DVP_VSYNC", "SMB1_SCK", "MSC1_CMD"}},
    {18, "PA18", {"SA2", "reserved", "reserved", "reserved"}},
    {22, "PA22", {"WAIT", "PWM1", "reserved", "reserved"}},
    {23, "PA23", {"reserved", "SFC_DT", "reserved", "reserved"}},
    {24, "PA24", {"reserved", "SFC_DR", "reserved", "reserved"}},
    {25, "PA25", {"reserved", "SFC_GPC", "reserved", "reserved"}},
    {26, "PA26", {"reserved", "SFC_CE1", "reserved", "reserved"}},
    {27, "PA27", {"reserved", "SFC_CLK", "reserved", "reserved"}},
    {28, "PA28", {"reserved", "SFC_CE0", "reserved", "reserved"}},
    {32, "PB00", {"MSC0_D0", "SSI_SLV_DT", "reserved", "reserved"}},
    {33, "PB01", {"MSC0_D1", "SSI_SLV_DR", "reserved", "reserved"}},
    {34, "PB02", {"MSC0_D2", "reserved", "reserved", "reserved"}},
    {35, "PB03", {"MSC0_D3", "reserved", "reserved", "reserved"}},
    {36, "PB04", {"MSC0_CLK", "SSI_SLV_CLK", "reserved", "reserved"}},
    {37, "PB05", {"MSC0_CMD", "SSI_SLV_CE0", "reserved", "reserved"}},
    {38, "PB06", {"GMAC_TXCLK", "reserved", "reserved", "SLCD_D0"}},
    {39, "PB07", {"GMAC_PHY_CLK", "reserved", "reserved", "SLCD_D1"}},
    {40, "PB08", {"GMAC_TXEN", "MSC1_CLK", "I2S_ADC_MCLK", "SLCD_D2"}},
    {41, "PB09", {"GMAC_RXDV", "MSC1_CMD", "I2S_SDTI", "SLCD_D3"}},
    {42, "PB10", {"GMAC_MDCK", "MSC1_D0", "I2S_SDTO", "SLCD_D4"}},
    {43, "PB11", {"GMAC_MDIO", "MSC1_D1", "reserved", "SLCD_D5"}},
    {45, "PB13", {"GMAC_TXD0", "MSC1_D2", "I2S_ADC_LRCK", "SLCD_D6"}},
    {46, "PB14", {"GMAC_TXD1", "MSC1_D3", "I2S_DAC_MCLK", "SLCD_D7"}},
    {47, "PB15", {"GMAC_RXD0", "reserved", "I2S_DAC_LRCK", "SLCD_WR"}},
    {48, "PB16", {"GMAC_RXD1", "reserved", "reserved", "SLCD_TE"}},
    {49, "PB17", {"PWM0", "SSI1_DT", "reserved", "reserved"}},
    {50, "PB18", {"PWM1", "SSI1_DR", "reserved", "reserved"}},
    {51, "PB19", {"UART0_RXD", "TDI", "reserved", "reserved"}},
    {52, "PB20", {"UART0_CTS", "reserved", "I2S_ADC_BCLK", "SLCD_CS"}},
    {53, "PB21", {"UART0_RTS", "reserved", "I2S_DAC_BCLK", "SLCD_DC"}},
    {54, "PB22", {"UART0_TXD", "TDO", "reserved", "SLCD_RDY"}},
    {55, "PB23", {"UART1_TXD", "TCK", "reserved", "reserved"}},
    {56, "PB24", {"UART1_RXD", "TMS", "reserved", "reserved"}},
    {57, "PB25", {"SMB1_SDA", "SSI1_CE0", "reserved", "reserved"}},
    {58, "PB26", {"SMB1_SCK", "SSI1_CLK", "reserved", "reserved"}},
    {59, "PB27", {"DRV_VBUS", "PWM2", "SSI1_DT", "reserved"}},
    {60, "PB28", {"reserved", "PWM3", "SSI1_DR", "DMIC_CLK"}},
    {61, "PB29", {"reserved", "reserved", "SSI1_CLK", "DMIC_DAT0"}},
    {62, "PB30", {"reserved", "reserved", "SSI1_CE0", "DMIC_DAT1"}},
    {63, "PB31", {"reserved", "reserved", "reserved", "reserved"}},
    {64, "PC00", {"reserved", "reserved", "reserved", "reserved"}},
    {65, "PC01", {"reserved", "reserved", "reserved", "reserved"}},
    {66, "PC02", {"MSC1_CLK", "SSI_SLV_CLK", "reserved", "reserved"}},
    {67, "PC03", {"MSC1_CMD", "SSI_SLV_CE0", "reserved", "reserved"}},
    {68, "PC04", {"MSC1_D0", "SSI_SLV_DT", "reserved", "reserved"}},
    {69, "PC05", {"MSC1_D1", "SSI_SLV_DR", "reserved", "reserved"}},
    {70, "PC06", {"MSC1_D2", "reserved", "reserved", "reserved"}},
    {71, "PC07", {"MSC1_D3", "reserved", "reserved", "reserved"}},
    {72, "PC08", {"SSI0_GPC", "UART0_TXD", "reserved", "SMB1_SDA"}},
    {73, "PC09", {"SSI0_CE1", "UART0_RXD", "reserved", "SMB1_SCK"}},
    {75, "PC11", {"SSI0_DR", "reserved", "UART2_CTS", "I2S_DAC_MCLK"}},
    {76, "PC12", {"SSI0_DT", "reserved", "UART2_RTS", "I2S_ADC_MCLK"}},
    {77, "PC13", {"SSI0_CLK", "DMIC_DAT0", "UART2_TXD", "reserved"}},
    {78, "PC14", {"SSI0_CE0", "DMIC_DAT1", "UART2_RXD", "reserved"}},
    {79, "PC15", {"reserved", "UART0_CTS", "reserved", "I2S_DAC_LRCK"}},
    {80, "PC16", {"reserved", "UART0_RTS", "reserved", "I2S_DAC_BCLK"}},
    {81, "PC17", {"PWM0", "reserved", "reserved", "I2S_SDTI"}},
    {82, "PC18", {"PWM1", "reserved", "reserved", "I2S_SDTO"}},
    {83, "PC19", {"PWM2", "reserved", "reserved", "I2S_ADC_BCLK"}},
    {84, "PC20", {"PWM3", "DMIC_CLK", "reserved", "I2S_ADC_LRCK"}},
    {85, "PC21", {"reserved", "reserved", "reserved", "reserved"}},
    {86, "PC22", {"reserved", "reserved", "reserved", "reserved"}},
    {87, "PC23", {"reserved", "reserved", "reserved", "reserved"}},
    {88, "PC24", {"reserved", "reserved", "reserved", "reserved"}},
    {89, "PC25", {"reserved", "reserved", "reserved", "reserved"}},
    {90, "PC26", {"reserved", "reserved", "reserved", "reserved"}},
};

static const ingenic_soc_t T31_padmux = {T31_pads, 77};

/* T21: 97 pads named, of 192 in the SoC's 6 ports. A pad no source
 * names is not here at all, which is a different answer from one
 * whose four functions are all unused.
 *
 * From the vendor kernel's board file, which names a DEVICE
 * rather than a wire -- a 12-bit DVP bus is twelve pads all
 * called DVP_PA_12BIT -- and only covers what it wires up.
 * There is no GPIO spec for this part.
 *   7456386fe28f8dae  platform.h
 *
 * What that source got wrong, recorded so nobody has to find
 * it twice:
 *   PD27 function 1: MII_PORTBDF vs DPU_PORTD_SLCD_8BIT
 *     one function slot given up: the silicon cannot do
 *     both and the file does not say which is real
 */
static const ingenic_pad_t T21_pads[] = {
    {0, "PA00", {"reserved", "DVP_PORTA", "reserved", "reserved"}},
    {1, "PA01", {"reserved", "DVP_PORTA", "reserved", "reserved"}},
    {2, "PA02", {"reserved", "DVP_PORTA", "reserved", "reserved"}},
    {3, "PA03", {"reserved", "DVP_PORTA", "reserved", "reserved"}},
    {4, "PA04", {"reserved", "DVP_PORTA", "reserved", "reserved"}},
    {5, "PA05", {"reserved", "DVP_PORTA", "reserved", "reserved"}},
    {6, "PA06", {"reserved", "DVP_PORTA", "reserved", "reserved"}},
    {7, "PA07", {"reserved", "DVP_PORTA", "reserved", "reserved"}},
    {8, "PA08", {"reserved", "DVP_PORTA", "reserved", "reserved"}},
    {9, "PA09", {"reserved", "DVP_PORTA", "reserved", "reserved"}},
    {10, "PA10", {"reserved", "DVP_PORTA", "reserved", "reserved"}},
    {11, "PA11", {"reserved", "DVP_PORTA", "reserved", "reserved"}},
    {12, "PA12", {"reserved", "I2C0_PORTA", "reserved", "reserved"}},
    {13, "PA13", {"reserved", "I2C0_PORTA", "reserved", "reserved"}},
    {14, "PA14", {"reserved", "DVP_PORTA", "reserved", "reserved"}},
    {15, "PA15", {"reserved", "MCLK_PORTA", "reserved", "reserved"}},
    {16, "PA16", {"reserved", "DVP_PORTA", "reserved", "reserved"}},
    {17, "PA17", {"reserved", "DVP_PORTA", "reserved", "reserved"}},
    {23, "PA23", {"reserved", "SFC_PORTA", "reserved", "reserved"}},
    {24, "PA24", {"reserved", "SFC_PORTA", "reserved", "reserved"}},
    {25, "PA25", {"reserved", "SFC_PORTA_QUAD", "reserved", "reserved"}},
    {26, "PA26", {"reserved", "SFC_PORTA_QUAD", "reserved", "reserved"}},
    {27, "PA27", {"reserved", "SFC_PORTA", "reserved", "reserved"}},
    {28, "PA28", {"reserved", "SFC_PORTA", "reserved", "reserved"}},
    {32, "PB00", {"MSC0_PORTB_4BIT", "reserved", "reserved", "reserved"}},
    {33, "PB01", {"MSC0_PORTB_4BIT", "reserved", "reserved", "reserved"}},
    {34, "PB02", {"MSC0_PORTB_4BIT", "reserved", "reserved", "reserved"}},
    {35, "PB03", {"MSC0_PORTB_4BIT", "reserved", "reserved", "reserved"}},
    {36, "PB04", {"MSC0_PORTB_4BIT", "MII_PORTBDF", "reserved", "reserved"}},
    {37, "PB05", {"MSC0_PORTB_4BIT", "reserved", "reserved", "reserved"}},
    {38, "PB06", {"GMAC_PORTB", "reserved", "GMAC_INTERNAL_PHY_PORTB_NO_ACTLED", "reserved"}},
    {39, "PB07", {"GMAC_PORTB", "reserved", "GMAC_INTERNAL_PHY_PORTB", "reserved"}},
    {40, "PB08", {"GMAC_PORTB", "SSI1_PORTC", "reserved", "reserved"}},
    {41, "PB09", {"GMAC_PORTB", "SSI1_PORTC", "reserved", "reserved"}},
    {42, "PB10", {"GMAC_PORTB", "SSI1_PORTC", "reserved", "reserved"}},
    {43, "PB11", {"GMAC_PORTB", "SSI1_PORTC", "reserved", "reserved"}},
    {45, "PB13", {"GMAC_PORTB", "SSI1_PORTC", "reserved", "reserved"}},
    {46, "PB14", {"GMAC_PORTB", "SSI1_PORTC", "reserved", "reserved"}},
    {47, "PB15", {"GMAC_PORTB", "reserved", "GMAC_INTERNAL_PHY_PORTB", "reserved"}},
    {48, "PB16", {"GMAC_PORTB", "reserved", "reserved", "reserved"}},
    {51, "PB19", {"UART0_PORTB", "reserved", "reserved", "reserved"}},
    {52, "PB20", {"UART0_PORTB", "reserved", "reserved", "reserved"}},
    {53, "PB21", {"UART0_PORTB", "reserved", "reserved", "reserved"}},
    {54, "PB22", {"UART0_PORTB", "reserved", "reserved", "reserved"}},
    {55, "PB23", {"UART1_PORTB", "reserved", "reserved", "reserved"}},
    {56, "PB24", {"UART1_PORTB", "reserved", "reserved", "reserved"}},
    {57, "PB25", {"I2C1_PORTB", "reserved", "reserved", "reserved"}},
    {58, "PB26", {"I2C1_PORTB", "reserved", "reserved", "reserved"}},
    {59, "PB27", {"OTG_DRVVUS", "reserved", "reserved", "reserved"}},
    {66, "PC02", {"MSC1_PORTC", "reserved", "reserved", "reserved"}},
    {67, "PC03", {"MSC1_PORTC", "reserved", "reserved", "reserved"}},
    {68, "PC04", {"MSC1_PORTC", "reserved", "reserved", "reserved"}},
    {69, "PC05", {"MSC1_PORTC", "reserved", "reserved", "reserved"}},
    {70, "PC06", {"MSC1_PORTC", "reserved", "reserved", "reserved"}},
    {71, "PC07", {"MSC1_PORTC", "reserved", "reserved", "reserved"}},
    {72, "PC08", {"SSI0_PORTC", "reserved", "I2C1_PORTC", "reserved"}},
    {73, "PC09", {"SSI0_PORTC", "reserved", "I2C1_PORTC", "reserved"}},
    {75, "PC11", {"SSI0_PORTC", "reserved", "reserved", "reserved"}},
    {76, "PC12", {"SSI0_PORTC", "reserved", "reserved", "reserved"}},
    {77, "PC13", {"SSI0_PORTC", "reserved", "UART2_PORTC", "reserved"}},
    {78, "PC14", {"SSI0_PORTC", "reserved", "UART2_PORTC", "reserved"}},
    {98, "PD02", {"DPU_PORTD_TFT_18BIT", "DPU_PORTD_SLCD", "reserved", "reserved"}},
    {99, "PD03", {"DPU_PORTD_TFT_18BIT", "DPU_PORTD_SLCD", "reserved", "reserved"}},
    {100, "PD04", {"DPU_PORTD_TFT_18BIT", "DPU_PORTD_SLCD", "reserved", "reserved"}},
    {101, "PD05", {"DPU_PORTD_TFT_18BIT", "DPU_PORTD_SLCD", "reserved", "reserved"}},
    {102, "PD06", {"DPU_PORTD_TFT_18BIT", "DPU_PORTD_SLCD", "reserved", "reserved"}},
    {103, "PD07", {"DPU_PORTD_TFT_18BIT", "DPU_PORTD_SLCD", "reserved", "reserved"}},
    {104, "PD08", {"DPU_PORTD_TFT_18BIT", "reserved", "reserved", "reserved"}},
    {105, "PD09", {"DPU_PORTD_TFT_18BIT", "DPU_PORTD_SLCD", "reserved", "reserved"}},
    {108, "PD12", {"DPU_PORTD_TFT_18BIT", "DPU_PORTD_SLCD", "reserved", "reserved"}},
    {109, "PD13", {"DPU_PORTD_TFT_18BIT", "DPU_PORTD_SLCD", "reserved", "reserved"}},
    {110, "PD14", {"DPU_PORTD_TFT_18BIT", "DPU_PORTD_SLCD_16BIT", "reserved", "reserved"}},
    {111, "PD15", {"DPU_PORTD_TFT_18BIT", "DPU_PORTD_SLCD_16BIT", "reserved", "reserved"}},
    {112, "PD16", {"DPU_PORTD_TFT_18BIT", "DPU_PORTD_SLCD_16BIT", "reserved", "reserved"}},
    {113, "PD17", {"DPU_PORTD_TFT_18BIT", "DPU_PORTD_SLCD_16BIT", "reserved", "reserved"}},
    {114, "PD18", {"DPU_PORTD_TFT_18BIT", "reserved", "reserved", "reserved"}},
    {115, "PD19", {"DPU_PORTD_TFT_18BIT", "DPU_PORTD_SLCD_8BIT", "reserved", "reserved"}},
    {118, "PD22", {"DPU_PORTD_TFT_18BIT", "DPU_PORTD_SLCD_16BIT", "reserved", "reserved"}},
    {119, "PD23", {"DPU_PORTD_TFT_18BIT", "DPU_PORTD_SLCD_16BIT", "reserved", "reserved"}},
    {120, "PD24", {"DPU_PORTD_TFT_18BIT", "DPU_PORTD_SLCD_16BIT", "reserved", "reserved"}},
    {121, "PD25", {"DPU_PORTD_TFT_18BIT", "DPU_PORTD_SLCD_16BIT", "reserved", "reserved"}},
    {122, "PD26", {"DPU_PORTD_TFT_18BIT", "MII_PORTBDF", "reserved", "reserved"}},
    {123, "PD27", {"DPU_PORTD_TFT_18BIT", "reserved", "reserved", "reserved"}},
    {124, "PD28", {"reserved", "MII_PORTBDF", "reserved", "reserved"}},
    {125, "PD29", {"reserved", "MII_PORTBDF", "reserved", "reserved"}},
    {164, "PF04", {"MII_PORTBDF", "reserved", "reserved", "reserved"}},
    {165, "PF05", {"MII_PORTBDF", "reserved", "reserved", "reserved"}},
    {166, "PF06", {"MII_PORTBDF", "reserved", "reserved", "reserved"}},
    {167, "PF07", {"MII_PORTBDF", "reserved", "reserved", "reserved"}},
    {168, "PF08", {"MII_PORTBDF", "reserved", "reserved", "reserved"}},
    {169, "PF09", {"MII_PORTBDF", "reserved", "reserved", "reserved"}},
    {170, "PF10", {"MII_PORTBDF", "reserved", "reserved", "reserved"}},
    {171, "PF11", {"MII_PORTBDF", "reserved", "reserved", "reserved"}},
    {172, "PF12", {"MII_PORTBDF", "reserved", "reserved", "reserved"}},
    {173, "PF13", {"MII_PORTBDF", "reserved", "reserved", "reserved"}},
    {174, "PF14", {"MII_PORTBDF", "reserved", "reserved", "reserved"}},
    {175, "PF15", {"MII_PORTBDF", "reserved", "reserved", "reserved"}},
};

static const ingenic_soc_t T21_padmux = {T21_pads, 97};

/* T23: 67 pads named, of 96 in the SoC's 3 ports. A pad no source
 * names is not here at all, which is a different answer from one
 * whose four functions are all unused.
 *
 * From the vendor kernel's board file, which names a DEVICE
 * rather than a wire -- a 12-bit DVP bus is twelve pads all
 * called DVP_PA_12BIT -- and only covers what it wires up.
 * There is no GPIO spec for this part.
 *   5c901739f084a1a1  platform.h
 *
 * What that source got wrong, recorded so nobody has to find
 * it twice:
 *   SSI0_PORTB_3: pins 0x1e0000000 reach past pin 31
 *     the pins past the end are dropped
 */
static const ingenic_pad_t T23_pads[] = {
    {0, "PA00", {"reserved", "DVP_PORTA", "reserved", "reserved"}},
    {1, "PA01", {"reserved", "DVP_PORTA", "reserved", "reserved"}},
    {2, "PA02", {"reserved", "DVP_PORTA", "reserved", "reserved"}},
    {3, "PA03", {"reserved", "DVP_PORTA", "reserved", "reserved"}},
    {4, "PA04", {"reserved", "DVP_PORTA", "reserved", "reserved"}},
    {5, "PA05", {"reserved", "DVP_PORTA", "reserved", "reserved"}},
    {6, "PA06", {"reserved", "DVP_PORTA", "UART1_PORTA", "reserved"}},
    {7, "PA07", {"reserved", "DVP_PORTA", "UART1_PORTA", "reserved"}},
    {8, "PA08", {"reserved", "DVP_PORTA", "reserved", "MSC1_PORTA"}},
    {9, "PA09", {"reserved", "DVP_PORTA", "reserved", "MSC1_PORTA"}},
    {10, "PA10", {"reserved", "DVP_PORTA", "reserved", "MSC1_PORTA"}},
    {11, "PA11", {"reserved", "DVP_PORTA", "reserved", "MSC1_PORTA"}},
    {12, "PA12", {"reserved", "I2C0_PORTA", "reserved", "reserved"}},
    {13, "PA13", {"reserved", "I2C0_PORTA", "reserved", "reserved"}},
    {14, "PA14", {"reserved", "DVP_PORTA", "reserved", "reserved"}},
    {15, "PA15", {"reserved", "MCLK_PORTA", "reserved", "reserved"}},
    {16, "PA16", {"reserved", "DVP_PORTA", "I2C1_PORTA", "MSC1_PORTA"}},
    {17, "PA17", {"reserved", "DVP_PORTA", "I2C1_PORTA", "MSC1_PORTA"}},
    {23, "PA23", {"reserved", "SFC_PORTA", "reserved", "reserved"}},
    {24, "PA24", {"reserved", "SFC_PORTA", "reserved", "reserved"}},
    {27, "PA27", {"reserved", "SFC_PORTA", "reserved", "reserved"}},
    {28, "PA28", {"reserved", "SFC_PORTA", "reserved", "reserved"}},
    {36, "PB04", {"reserved", "MII_PORTBDF", "reserved", "reserved"}},
    {38, "PB06", {"GMAC_PORTB", "reserved", "reserved", "reserved"}},
    {39, "PB07", {"GMAC_PORTB", "reserved", "reserved", "reserved"}},
    {40, "PB08", {"GMAC_PORTB", "MSC1_PORTB", "reserved", "reserved"}},
    {41, "PB09", {"GMAC_PORTB", "MSC1_PORTB", "reserved", "reserved"}},
    {42, "PB10", {"GMAC_PORTB", "MSC1_PORTB", "reserved", "reserved"}},
    {43, "PB11", {"GMAC_PORTB", "MSC1_PORTB", "reserved", "reserved"}},
    {45, "PB13", {"GMAC_PORTB", "MSC1_PORTB", "reserved", "reserved"}},
    {46, "PB14", {"GMAC_PORTB", "MSC1_PORTB", "reserved", "reserved"}},
    {47, "PB15", {"GMAC_PORTB", "SSI0_PORTB", "SFC_PORTA_QUAD", "reserved"}},
    {48, "PB16", {"GMAC_PORTB", "SSI0_PORTB", "SFC_PORTA_QUAD", "reserved"}},
    {49, "PB17", {"reserved", "SSI0_PORTB", "UART2_PORTB", "reserved"}},
    {50, "PB18", {"reserved", "SSI0_PORTB", "UART2_PORTB", "reserved"}},
    {51, "PB19", {"UART0_PORTB", "reserved", "reserved", "reserved"}},
    {52, "PB20", {"UART0_PORTB_FC", "reserved", "I2C2_PORTB", "reserved"}},
    {53, "PB21", {"UART0_PORTB_FC", "reserved", "I2C2_PORTB", "reserved"}},
    {54, "PB22", {"UART0_PORTB", "reserved", "reserved", "reserved"}},
    {55, "PB23", {"UART1_PORTB", "reserved", "reserved", "reserved"}},
    {56, "PB24", {"UART1_PORTB", "reserved", "reserved", "reserved"}},
    {57, "PB25", {"I2C1_PORTB", "reserved", "UART2_PORTB_FC", "reserved"}},
    {58, "PB26", {"I2C1_PORTB", "reserved", "UART2_PORTB_FC", "reserved"}},
    {59, "PB27", {"OTG_DRVVUS", "reserved", "SSI0_PORTB", "reserved"}},
    {60, "PB28", {"reserved", "reserved", "SSI0_PORTB", "DMIC_PORTC"}},
    {61, "PB29", {"reserved", "reserved", "SSI0_PORTB", "DMIC_PORTC"}},
    {62, "PB30", {"reserved", "reserved", "SSI0_PORTB", "DMIC_PORTC"}},
    {63, "PB31", {"reserved", "reserved", "SSI0_PORTB_3", "reserved"}},
    {66, "PC02", {"MSC1_PORTC", "reserved", "reserved", "reserved"}},
    {67, "PC03", {"MSC1_PORTC", "reserved", "reserved", "reserved"}},
    {68, "PC04", {"MSC1_PORTC", "reserved", "reserved", "reserved"}},
    {69, "PC05", {"MSC1_PORTC", "reserved", "reserved", "reserved"}},
    {70, "PC06", {"MSC1_PORTC", "reserved", "reserved", "reserved"}},
    {71, "PC07", {"MSC1_PORTC", "reserved", "reserved", "reserved"}},
    {72, "PC08", {"reserved", "reserved", "reserved", "I2C1_PORTC"}},
    {73, "PC09", {"reserved", "reserved", "reserved", "I2C1_PORTC"}},
    {75, "PC11", {"reserved", "reserved", "UART2_PORTC_FC", "reserved"}},
    {76, "PC12", {"reserved", "reserved", "UART2_PORTC_FC", "reserved"}},
    {77, "PC13", {"reserved", "reserved", "UART2_PORTC", "reserved"}},
    {78, "PC14", {"reserved", "reserved", "UART2_PORTC", "reserved"}},
    {82, "PC18", {"I2S_PORTC", "reserved", "reserved", "reserved"}},
    {83, "PC19", {"I2S_PORTC", "reserved", "reserved", "reserved"}},
    {84, "PC20", {"I2S_PORTC", "reserved", "reserved", "reserved"}},
    {85, "PC21", {"I2S_PORTC", "reserved", "reserved", "reserved"}},
    {86, "PC22", {"I2S_PORTC", "reserved", "reserved", "reserved"}},
    {87, "PC23", {"I2S_PORTC", "reserved", "reserved", "reserved"}},
    {88, "PC24", {"I2S_PORTC", "reserved", "reserved", "reserved"}},
};

static const ingenic_soc_t T23_padmux = {T23_pads, 67};

#endif /* HAL_INGENIC_PADMUX_H */
