/* Generated by tools/gen_ingenic_padmux.py -- do not edit.
 *
 * The four device functions of each pad. Ingenic selects between them
 * with one bit each in the port's INT, MSK, PAT1 and PAT0 registers
 * rather than with a field, so these are names and nothing else:
 * src/hal/ingenic_padmux.c holds the registers.
 *
 * Regenerate with:
 *   tools/gen_ingenic_padmux.py \
 *       --soc T31 --spec T31_H.3_gpio_spec.pdf \
 *       --soc T21 --spec platform.h \
 *       --soc T23 --spec platform.h \
 *       --soc T40 --spec t40-pinctrl.dtsi
 */

#ifndef HAL_INGENIC_PADMUX_H
#define HAL_INGENIC_PADMUX_H

#include "hal/ingenic_padmux_types.h"

/* T31: 77 pads named, of 96 in the SoC's 3 ports. A pad no source
 * names is not here at all, which is a different answer from one
 * whose four functions are all unused.
 *
 * From the GPIO spec's port summary tables: FUNCTION0..3 per
 * pad, named per wire.
 *   bb1d41a16f9809da  T31_H.3_gpio_spec.pdf
 */
static const ingenic_pad_t T31_pads[] = {
    {6, PMX_PA06, {PMX_SD0, PMX_DVP_D6, PMX_UART1_TXD, PMX_reserved}},
    {7, PMX_PA07, {PMX_SD1, PMX_DVP_D7, PMX_UART1_RXD, PMX_reserved}},
    {8, PMX_PA08, {PMX_SD2, PMX_DVP_D8, PMX_UART2_CTS, PMX_MSC1_D0}},
    {9, PMX_PA09, {PMX_SD3, PMX_DVP_D9, PMX_UART2_RTS, PMX_MSC1_D1}},
    {10, PMX_PA10, {PMX_SD4, PMX_DVP_D10, PMX_UART2_TXD, PMX_MSC1_D2}},
    {11, PMX_PA11, {PMX_SD5, PMX_DVP_D11, PMX_UART2_RXD, PMX_MSC1_D3}},
    {12, PMX_PA12, {PMX_SD6, PMX_SMB0_SDA, PMX_reserved, PMX_reserved}},
    {13, PMX_PA13, {PMX_SD7, PMX_SMB0_SCK, PMX_reserved, PMX_reserved}},
    {14, PMX_PA14, {PMX_SA0, PMX_DVP_PCLK, PMX_PWM0, PMX_reserved}},
    {15, PMX_PA15, {PMX_SA1, PMX_DVP_MCLK, PMX_reserved, PMX_reserved}},
    {16, PMX_PA16, {PMX_CS2, PMX_DVP_HSYNC, PMX_SMB1_SDA, PMX_MSC1_CLK}},
    {17, PMX_PA17, {PMX_RD, PMX_DVP_VSYNC, PMX_SMB1_SCK, PMX_MSC1_CMD}},
    {18, PMX_PA18, {PMX_SA2, PMX_reserved, PMX_reserved, PMX_reserved}},
    {22, PMX_PA22, {PMX_WAIT, PMX_PWM1, PMX_reserved, PMX_reserved}},
    {23, PMX_PA23, {PMX_reserved, PMX_SFC_DT, PMX_reserved, PMX_reserved}},
    {24, PMX_PA24, {PMX_reserved, PMX_SFC_DR, PMX_reserved, PMX_reserved}},
    {25, PMX_PA25, {PMX_reserved, PMX_SFC_GPC, PMX_reserved, PMX_reserved}},
    {26, PMX_PA26, {PMX_reserved, PMX_SFC_CE1, PMX_reserved, PMX_reserved}},
    {27, PMX_PA27, {PMX_reserved, PMX_SFC_CLK, PMX_reserved, PMX_reserved}},
    {28, PMX_PA28, {PMX_reserved, PMX_SFC_CE0, PMX_reserved, PMX_reserved}},
    {32, PMX_PB00, {PMX_MSC0_D0, PMX_SSI_SLV_DT, PMX_reserved, PMX_reserved}},
    {33, PMX_PB01, {PMX_MSC0_D1, PMX_SSI_SLV_DR, PMX_reserved, PMX_reserved}},
    {34, PMX_PB02, {PMX_MSC0_D2, PMX_reserved, PMX_reserved, PMX_reserved}},
    {35, PMX_PB03, {PMX_MSC0_D3, PMX_reserved, PMX_reserved, PMX_reserved}},
    {36, PMX_PB04, {PMX_MSC0_CLK, PMX_SSI_SLV_CLK, PMX_reserved, PMX_reserved}},
    {37, PMX_PB05, {PMX_MSC0_CMD, PMX_SSI_SLV_CE0, PMX_reserved, PMX_reserved}},
    {38, PMX_PB06, {PMX_GMAC_TXCLK, PMX_reserved, PMX_reserved, PMX_SLCD_D0}},
    {39, PMX_PB07, {PMX_GMAC_PHY_CLK, PMX_reserved, PMX_reserved, PMX_SLCD_D1}},
    {40, PMX_PB08, {PMX_GMAC_TXEN, PMX_MSC1_CLK, PMX_I2S_ADC_MCLK, PMX_SLCD_D2}},
    {41, PMX_PB09, {PMX_GMAC_RXDV, PMX_MSC1_CMD, PMX_I2S_SDTI, PMX_SLCD_D3}},
    {42, PMX_PB10, {PMX_GMAC_MDCK, PMX_MSC1_D0, PMX_I2S_SDTO, PMX_SLCD_D4}},
    {43, PMX_PB11, {PMX_GMAC_MDIO, PMX_MSC1_D1, PMX_reserved, PMX_SLCD_D5}},
    {45, PMX_PB13, {PMX_GMAC_TXD0, PMX_MSC1_D2, PMX_I2S_ADC_LRCK, PMX_SLCD_D6}},
    {46, PMX_PB14, {PMX_GMAC_TXD1, PMX_MSC1_D3, PMX_I2S_DAC_MCLK, PMX_SLCD_D7}},
    {47, PMX_PB15, {PMX_GMAC_RXD0, PMX_reserved, PMX_I2S_DAC_LRCK, PMX_SLCD_WR}},
    {48, PMX_PB16, {PMX_GMAC_RXD1, PMX_reserved, PMX_reserved, PMX_SLCD_TE}},
    {49, PMX_PB17, {PMX_PWM0, PMX_SSI1_DT, PMX_reserved, PMX_reserved}},
    {50, PMX_PB18, {PMX_PWM1, PMX_SSI1_DR, PMX_reserved, PMX_reserved}},
    {51, PMX_PB19, {PMX_UART0_RXD, PMX_TDI, PMX_reserved, PMX_reserved}},
    {52, PMX_PB20, {PMX_UART0_CTS, PMX_reserved, PMX_I2S_ADC_BCLK, PMX_SLCD_CS}},
    {53, PMX_PB21, {PMX_UART0_RTS, PMX_reserved, PMX_I2S_DAC_BCLK, PMX_SLCD_DC}},
    {54, PMX_PB22, {PMX_UART0_TXD, PMX_TDO, PMX_reserved, PMX_SLCD_RDY}},
    {55, PMX_PB23, {PMX_UART1_TXD, PMX_TCK, PMX_reserved, PMX_reserved}},
    {56, PMX_PB24, {PMX_UART1_RXD, PMX_TMS, PMX_reserved, PMX_reserved}},
    {57, PMX_PB25, {PMX_SMB1_SDA, PMX_SSI1_CE0, PMX_reserved, PMX_reserved}},
    {58, PMX_PB26, {PMX_SMB1_SCK, PMX_SSI1_CLK, PMX_reserved, PMX_reserved}},
    {59, PMX_PB27, {PMX_DRV_VBUS, PMX_PWM2, PMX_SSI1_DT, PMX_reserved}},
    {60, PMX_PB28, {PMX_reserved, PMX_PWM3, PMX_SSI1_DR, PMX_DMIC_CLK}},
    {61, PMX_PB29, {PMX_reserved, PMX_reserved, PMX_SSI1_CLK, PMX_DMIC_DAT0}},
    {62, PMX_PB30, {PMX_reserved, PMX_reserved, PMX_SSI1_CE0, PMX_DMIC_DAT1}},
    {63, PMX_PB31, {PMX_reserved, PMX_reserved, PMX_reserved, PMX_reserved}},
    {64, PMX_PC00, {PMX_reserved, PMX_reserved, PMX_reserved, PMX_reserved}},
    {65, PMX_PC01, {PMX_reserved, PMX_reserved, PMX_reserved, PMX_reserved}},
    {66, PMX_PC02, {PMX_MSC1_CLK, PMX_SSI_SLV_CLK, PMX_reserved, PMX_reserved}},
    {67, PMX_PC03, {PMX_MSC1_CMD, PMX_SSI_SLV_CE0, PMX_reserved, PMX_reserved}},
    {68, PMX_PC04, {PMX_MSC1_D0, PMX_SSI_SLV_DT, PMX_reserved, PMX_reserved}},
    {69, PMX_PC05, {PMX_MSC1_D1, PMX_SSI_SLV_DR, PMX_reserved, PMX_reserved}},
    {70, PMX_PC06, {PMX_MSC1_D2, PMX_reserved, PMX_reserved, PMX_reserved}},
    {71, PMX_PC07, {PMX_MSC1_D3, PMX_reserved, PMX_reserved, PMX_reserved}},
    {72, PMX_PC08, {PMX_SSI0_GPC, PMX_UART0_TXD, PMX_reserved, PMX_SMB1_SDA}},
    {73, PMX_PC09, {PMX_SSI0_CE1, PMX_UART0_RXD, PMX_reserved, PMX_SMB1_SCK}},
    {75, PMX_PC11, {PMX_SSI0_DR, PMX_reserved, PMX_UART2_CTS, PMX_I2S_DAC_MCLK}},
    {76, PMX_PC12, {PMX_SSI0_DT, PMX_reserved, PMX_UART2_RTS, PMX_I2S_ADC_MCLK}},
    {77, PMX_PC13, {PMX_SSI0_CLK, PMX_DMIC_DAT0, PMX_UART2_TXD, PMX_reserved}},
    {78, PMX_PC14, {PMX_SSI0_CE0, PMX_DMIC_DAT1, PMX_UART2_RXD, PMX_reserved}},
    {79, PMX_PC15, {PMX_reserved, PMX_UART0_CTS, PMX_reserved, PMX_I2S_DAC_LRCK}},
    {80, PMX_PC16, {PMX_reserved, PMX_UART0_RTS, PMX_reserved, PMX_I2S_DAC_BCLK}},
    {81, PMX_PC17, {PMX_PWM0, PMX_reserved, PMX_reserved, PMX_I2S_SDTI}},
    {82, PMX_PC18, {PMX_PWM1, PMX_reserved, PMX_reserved, PMX_I2S_SDTO}},
    {83, PMX_PC19, {PMX_PWM2, PMX_reserved, PMX_reserved, PMX_I2S_ADC_BCLK}},
    {84, PMX_PC20, {PMX_PWM3, PMX_DMIC_CLK, PMX_reserved, PMX_I2S_ADC_LRCK}},
    {85, PMX_PC21, {PMX_reserved, PMX_reserved, PMX_reserved, PMX_reserved}},
    {86, PMX_PC22, {PMX_reserved, PMX_reserved, PMX_reserved, PMX_reserved}},
    {87, PMX_PC23, {PMX_reserved, PMX_reserved, PMX_reserved, PMX_reserved}},
    {88, PMX_PC24, {PMX_reserved, PMX_reserved, PMX_reserved, PMX_reserved}},
    {89, PMX_PC25, {PMX_reserved, PMX_reserved, PMX_reserved, PMX_reserved}},
    {90, PMX_PC26, {PMX_reserved, PMX_reserved, PMX_reserved, PMX_reserved}},
};

static const ingenic_soc_t T31_padmux = {T31_pads, 77};

/* T21: 97 pads named, of 192 in the SoC's 6 ports. A pad no source
 * names is not here at all, which is a different answer from one
 * whose four functions are all unused.
 *
 * From the vendor kernel's board file, which names a DEVICE
 * rather than a wire -- a 12-bit DVP bus is twelve pads all
 * called DVP_PA_12BIT -- and only covers what it wires up.
 * There is no GPIO spec for this part.
 *   7456386fe28f8dae  platform.h
 *
 * What that source got wrong, recorded so nobody has to find
 * it twice:
 *   PD27 function 1: MII_PORTBDF vs DPU_PORTD_SLCD_8BIT
 *     one function slot given up: the silicon cannot do
 *     both and the file does not say which is real
 */
static const ingenic_pad_t T21_pads[] = {
    {0, PMX_PA00, {PMX_reserved, PMX_DVP_PORTA, PMX_reserved, PMX_reserved}},
    {1, PMX_PA01, {PMX_reserved, PMX_DVP_PORTA, PMX_reserved, PMX_reserved}},
    {2, PMX_PA02, {PMX_reserved, PMX_DVP_PORTA, PMX_reserved, PMX_reserved}},
    {3, PMX_PA03, {PMX_reserved, PMX_DVP_PORTA, PMX_reserved, PMX_reserved}},
    {4, PMX_PA04, {PMX_reserved, PMX_DVP_PORTA, PMX_reserved, PMX_reserved}},
    {5, PMX_PA05, {PMX_reserved, PMX_DVP_PORTA, PMX_reserved, PMX_reserved}},
    {6, PMX_PA06, {PMX_reserved, PMX_DVP_PORTA, PMX_reserved, PMX_reserved}},
    {7, PMX_PA07, {PMX_reserved, PMX_DVP_PORTA, PMX_reserved, PMX_reserved}},
    {8, PMX_PA08, {PMX_reserved, PMX_DVP_PORTA, PMX_reserved, PMX_reserved}},
    {9, PMX_PA09, {PMX_reserved, PMX_DVP_PORTA, PMX_reserved, PMX_reserved}},
    {10, PMX_PA10, {PMX_reserved, PMX_DVP_PORTA, PMX_reserved, PMX_reserved}},
    {11, PMX_PA11, {PMX_reserved, PMX_DVP_PORTA, PMX_reserved, PMX_reserved}},
    {12, PMX_PA12, {PMX_reserved, PMX_I2C0_PORTA, PMX_reserved, PMX_reserved}},
    {13, PMX_PA13, {PMX_reserved, PMX_I2C0_PORTA, PMX_reserved, PMX_reserved}},
    {14, PMX_PA14, {PMX_reserved, PMX_DVP_PORTA, PMX_reserved, PMX_reserved}},
    {15, PMX_PA15, {PMX_reserved, PMX_MCLK_PORTA, PMX_reserved, PMX_reserved}},
    {16, PMX_PA16, {PMX_reserved, PMX_DVP_PORTA, PMX_reserved, PMX_reserved}},
    {17, PMX_PA17, {PMX_reserved, PMX_DVP_PORTA, PMX_reserved, PMX_reserved}},
    {23, PMX_PA23, {PMX_reserved, PMX_SFC_PORTA, PMX_reserved, PMX_reserved}},
    {24, PMX_PA24, {PMX_reserved, PMX_SFC_PORTA, PMX_reserved, PMX_reserved}},
    {25, PMX_PA25, {PMX_reserved, PMX_SFC_PORTA_QUAD, PMX_reserved, PMX_reserved}},
    {26, PMX_PA26, {PMX_reserved, PMX_SFC_PORTA_QUAD, PMX_reserved, PMX_reserved}},
    {27, PMX_PA27, {PMX_reserved, PMX_SFC_PORTA, PMX_reserved, PMX_reserved}},
    {28, PMX_PA28, {PMX_reserved, PMX_SFC_PORTA, PMX_reserved, PMX_reserved}},
    {32, PMX_PB00, {PMX_MSC0_PORTB_4BIT, PMX_reserved, PMX_reserved, PMX_reserved}},
    {33, PMX_PB01, {PMX_MSC0_PORTB_4BIT, PMX_reserved, PMX_reserved, PMX_reserved}},
    {34, PMX_PB02, {PMX_MSC0_PORTB_4BIT, PMX_reserved, PMX_reserved, PMX_reserved}},
    {35, PMX_PB03, {PMX_MSC0_PORTB_4BIT, PMX_reserved, PMX_reserved, PMX_reserved}},
    {36, PMX_PB04, {PMX_MSC0_PORTB_4BIT, PMX_MII_PORTBDF, PMX_reserved, PMX_reserved}},
    {37, PMX_PB05, {PMX_MSC0_PORTB_4BIT, PMX_reserved, PMX_reserved, PMX_reserved}},
    {38, PMX_PB06, {PMX_GMAC_PORTB, PMX_reserved, PMX_GMAC_INTERNAL_PHY_PORTB_NO_ACTLED, PMX_reserved}},
    {39, PMX_PB07, {PMX_GMAC_PORTB, PMX_reserved, PMX_GMAC_INTERNAL_PHY_PORTB, PMX_reserved}},
    {40, PMX_PB08, {PMX_GMAC_PORTB, PMX_SSI1_PORTC, PMX_reserved, PMX_reserved}},
    {41, PMX_PB09, {PMX_GMAC_PORTB, PMX_SSI1_PORTC, PMX_reserved, PMX_reserved}},
    {42, PMX_PB10, {PMX_GMAC_PORTB, PMX_SSI1_PORTC, PMX_reserved, PMX_reserved}},
    {43, PMX_PB11, {PMX_GMAC_PORTB, PMX_SSI1_PORTC, PMX_reserved, PMX_reserved}},
    {45, PMX_PB13, {PMX_GMAC_PORTB, PMX_SSI1_PORTC, PMX_reserved, PMX_reserved}},
    {46, PMX_PB14, {PMX_GMAC_PORTB, PMX_SSI1_PORTC, PMX_reserved, PMX_reserved}},
    {47, PMX_PB15, {PMX_GMAC_PORTB, PMX_reserved, PMX_GMAC_INTERNAL_PHY_PORTB, PMX_reserved}},
    {48, PMX_PB16, {PMX_GMAC_PORTB, PMX_reserved, PMX_reserved, PMX_reserved}},
    {51, PMX_PB19, {PMX_UART0_PORTB, PMX_reserved, PMX_reserved, PMX_reserved}},
    {52, PMX_PB20, {PMX_UART0_PORTB, PMX_reserved, PMX_reserved, PMX_reserved}},
    {53, PMX_PB21, {PMX_UART0_PORTB, PMX_reserved, PMX_reserved, PMX_reserved}},
    {54, PMX_PB22, {PMX_UART0_PORTB, PMX_reserved, PMX_reserved, PMX_reserved}},
    {55, PMX_PB23, {PMX_UART1_PORTB, PMX_reserved, PMX_reserved, PMX_reserved}},
    {56, PMX_PB24, {PMX_UART1_PORTB, PMX_reserved, PMX_reserved, PMX_reserved}},
    {57, PMX_PB25, {PMX_I2C1_PORTB, PMX_reserved, PMX_reserved, PMX_reserved}},
    {58, PMX_PB26, {PMX_I2C1_PORTB, PMX_reserved, PMX_reserved, PMX_reserved}},
    {59, PMX_PB27, {PMX_OTG_DRVVUS, PMX_reserved, PMX_reserved, PMX_reserved}},
    {66, PMX_PC02, {PMX_MSC1_PORTC, PMX_reserved, PMX_reserved, PMX_reserved}},
    {67, PMX_PC03, {PMX_MSC1_PORTC, PMX_reserved, PMX_reserved, PMX_reserved}},
    {68, PMX_PC04, {PMX_MSC1_PORTC, PMX_reserved, PMX_reserved, PMX_reserved}},
    {69, PMX_PC05, {PMX_MSC1_PORTC, PMX_reserved, PMX_reserved, PMX_reserved}},
    {70, PMX_PC06, {PMX_MSC1_PORTC, PMX_reserved, PMX_reserved, PMX_reserved}},
    {71, PMX_PC07, {PMX_MSC1_PORTC, PMX_reserved, PMX_reserved, PMX_reserved}},
    {72, PMX_PC08, {PMX_SSI0_PORTC, PMX_reserved, PMX_I2C1_PORTC, PMX_reserved}},
    {73, PMX_PC09, {PMX_SSI0_PORTC, PMX_reserved, PMX_I2C1_PORTC, PMX_reserved}},
    {75, PMX_PC11, {PMX_SSI0_PORTC, PMX_reserved, PMX_reserved, PMX_reserved}},
    {76, PMX_PC12, {PMX_SSI0_PORTC, PMX_reserved, PMX_reserved, PMX_reserved}},
    {77, PMX_PC13, {PMX_SSI0_PORTC, PMX_reserved, PMX_UART2_PORTC, PMX_reserved}},
    {78, PMX_PC14, {PMX_SSI0_PORTC, PMX_reserved, PMX_UART2_PORTC, PMX_reserved}},
    {98, PMX_PD02, {PMX_DPU_PORTD_TFT_18BIT, PMX_DPU_PORTD_SLCD, PMX_reserved, PMX_reserved}},
    {99, PMX_PD03, {PMX_DPU_PORTD_TFT_18BIT, PMX_DPU_PORTD_SLCD, PMX_reserved, PMX_reserved}},
    {100, PMX_PD04, {PMX_DPU_PORTD_TFT_18BIT, PMX_DPU_PORTD_SLCD, PMX_reserved, PMX_reserved}},
    {101, PMX_PD05, {PMX_DPU_PORTD_TFT_18BIT, PMX_DPU_PORTD_SLCD, PMX_reserved, PMX_reserved}},
    {102, PMX_PD06, {PMX_DPU_PORTD_TFT_18BIT, PMX_DPU_PORTD_SLCD, PMX_reserved, PMX_reserved}},
    {103, PMX_PD07, {PMX_DPU_PORTD_TFT_18BIT, PMX_DPU_PORTD_SLCD, PMX_reserved, PMX_reserved}},
    {104, PMX_PD08, {PMX_DPU_PORTD_TFT_18BIT, PMX_reserved, PMX_reserved, PMX_reserved}},
    {105, PMX_PD09, {PMX_DPU_PORTD_TFT_18BIT, PMX_DPU_PORTD_SLCD, PMX_reserved, PMX_reserved}},
    {108, PMX_PD12, {PMX_DPU_PORTD_TFT_18BIT, PMX_DPU_PORTD_SLCD, PMX_reserved, PMX_reserved}},
    {109, PMX_PD13, {PMX_DPU_PORTD_TFT_18BIT, PMX_DPU_PORTD_SLCD, PMX_reserved, PMX_reserved}},
    {110, PMX_PD14, {PMX_DPU_PORTD_TFT_18BIT, PMX_DPU_PORTD_SLCD_16BIT, PMX_reserved, PMX_reserved}},
    {111, PMX_PD15, {PMX_DPU_PORTD_TFT_18BIT, PMX_DPU_PORTD_SLCD_16BIT, PMX_reserved, PMX_reserved}},
    {112, PMX_PD16, {PMX_DPU_PORTD_TFT_18BIT, PMX_DPU_PORTD_SLCD_16BIT, PMX_reserved, PMX_reserved}},
    {113, PMX_PD17, {PMX_DPU_PORTD_TFT_18BIT, PMX_DPU_PORTD_SLCD_16BIT, PMX_reserved, PMX_reserved}},
    {114, PMX_PD18, {PMX_DPU_PORTD_TFT_18BIT, PMX_reserved, PMX_reserved, PMX_reserved}},
    {115, PMX_PD19, {PMX_DPU_PORTD_TFT_18BIT, PMX_DPU_PORTD_SLCD_8BIT, PMX_reserved, PMX_reserved}},
    {118, PMX_PD22, {PMX_DPU_PORTD_TFT_18BIT, PMX_DPU_PORTD_SLCD_16BIT, PMX_reserved, PMX_reserved}},
    {119, PMX_PD23, {PMX_DPU_PORTD_TFT_18BIT, PMX_DPU_PORTD_SLCD_16BIT, PMX_reserved, PMX_reserved}},
    {120, PMX_PD24, {PMX_DPU_PORTD_TFT_18BIT, PMX_DPU_PORTD_SLCD_16BIT, PMX_reserved, PMX_reserved}},
    {121, PMX_PD25, {PMX_DPU_PORTD_TFT_18BIT, PMX_DPU_PORTD_SLCD_16BIT, PMX_reserved, PMX_reserved}},
    {122, PMX_PD26, {PMX_DPU_PORTD_TFT_18BIT, PMX_MII_PORTBDF, PMX_reserved, PMX_reserved}},
    {123, PMX_PD27, {PMX_DPU_PORTD_TFT_18BIT, PMX_reserved, PMX_reserved, PMX_reserved}},
    {124, PMX_PD28, {PMX_reserved, PMX_MII_PORTBDF, PMX_reserved, PMX_reserved}},
    {125, PMX_PD29, {PMX_reserved, PMX_MII_PORTBDF, PMX_reserved, PMX_reserved}},
    {164, PMX_PF04, {PMX_MII_PORTBDF, PMX_reserved, PMX_reserved, PMX_reserved}},
    {165, PMX_PF05, {PMX_MII_PORTBDF, PMX_reserved, PMX_reserved, PMX_reserved}},
    {166, PMX_PF06, {PMX_MII_PORTBDF, PMX_reserved, PMX_reserved, PMX_reserved}},
    {167, PMX_PF07, {PMX_MII_PORTBDF, PMX_reserved, PMX_reserved, PMX_reserved}},
    {168, PMX_PF08, {PMX_MII_PORTBDF, PMX_reserved, PMX_reserved, PMX_reserved}},
    {169, PMX_PF09, {PMX_MII_PORTBDF, PMX_reserved, PMX_reserved, PMX_reserved}},
    {170, PMX_PF10, {PMX_MII_PORTBDF, PMX_reserved, PMX_reserved, PMX_reserved}},
    {171, PMX_PF11, {PMX_MII_PORTBDF, PMX_reserved, PMX_reserved, PMX_reserved}},
    {172, PMX_PF12, {PMX_MII_PORTBDF, PMX_reserved, PMX_reserved, PMX_reserved}},
    {173, PMX_PF13, {PMX_MII_PORTBDF, PMX_reserved, PMX_reserved, PMX_reserved}},
    {174, PMX_PF14, {PMX_MII_PORTBDF, PMX_reserved, PMX_reserved, PMX_reserved}},
    {175, PMX_PF15, {PMX_MII_PORTBDF, PMX_reserved, PMX_reserved, PMX_reserved}},
};

static const ingenic_soc_t T21_padmux = {T21_pads, 97};

/* T23: 67 pads named, of 96 in the SoC's 3 ports. A pad no source
 * names is not here at all, which is a different answer from one
 * whose four functions are all unused.
 *
 * From the vendor kernel's board file, which names a DEVICE
 * rather than a wire -- a 12-bit DVP bus is twelve pads all
 * called DVP_PA_12BIT -- and only covers what it wires up.
 * There is no GPIO spec for this part.
 *   5c901739f084a1a1  platform.h
 *
 * What that source got wrong, recorded so nobody has to find
 * it twice:
 *   SSI0_PORTB_3: pins 0x1e0000000 reach past pin 31
 *     the pins past the end are dropped
 */
static const ingenic_pad_t T23_pads[] = {
    {0, PMX_PA00, {PMX_reserved, PMX_DVP_PORTA, PMX_reserved, PMX_reserved}},
    {1, PMX_PA01, {PMX_reserved, PMX_DVP_PORTA, PMX_reserved, PMX_reserved}},
    {2, PMX_PA02, {PMX_reserved, PMX_DVP_PORTA, PMX_reserved, PMX_reserved}},
    {3, PMX_PA03, {PMX_reserved, PMX_DVP_PORTA, PMX_reserved, PMX_reserved}},
    {4, PMX_PA04, {PMX_reserved, PMX_DVP_PORTA, PMX_reserved, PMX_reserved}},
    {5, PMX_PA05, {PMX_reserved, PMX_DVP_PORTA, PMX_reserved, PMX_reserved}},
    {6, PMX_PA06, {PMX_reserved, PMX_DVP_PORTA, PMX_UART1_PORTA, PMX_reserved}},
    {7, PMX_PA07, {PMX_reserved, PMX_DVP_PORTA, PMX_UART1_PORTA, PMX_reserved}},
    {8, PMX_PA08, {PMX_reserved, PMX_DVP_PORTA, PMX_reserved, PMX_MSC1_PORTA}},
    {9, PMX_PA09, {PMX_reserved, PMX_DVP_PORTA, PMX_reserved, PMX_MSC1_PORTA}},
    {10, PMX_PA10, {PMX_reserved, PMX_DVP_PORTA, PMX_reserved, PMX_MSC1_PORTA}},
    {11, PMX_PA11, {PMX_reserved, PMX_DVP_PORTA, PMX_reserved, PMX_MSC1_PORTA}},
    {12, PMX_PA12, {PMX_reserved, PMX_I2C0_PORTA, PMX_reserved, PMX_reserved}},
    {13, PMX_PA13, {PMX_reserved, PMX_I2C0_PORTA, PMX_reserved, PMX_reserved}},
    {14, PMX_PA14, {PMX_reserved, PMX_DVP_PORTA, PMX_reserved, PMX_reserved}},
    {15, PMX_PA15, {PMX_reserved, PMX_MCLK_PORTA, PMX_reserved, PMX_reserved}},
    {16, PMX_PA16, {PMX_reserved, PMX_DVP_PORTA, PMX_I2C1_PORTA, PMX_MSC1_PORTA}},
    {17, PMX_PA17, {PMX_reserved, PMX_DVP_PORTA, PMX_I2C1_PORTA, PMX_MSC1_PORTA}},
    {23, PMX_PA23, {PMX_reserved, PMX_SFC_PORTA, PMX_reserved, PMX_reserved}},
    {24, PMX_PA24, {PMX_reserved, PMX_SFC_PORTA, PMX_reserved, PMX_reserved}},
    {27, PMX_PA27, {PMX_reserved, PMX_SFC_PORTA, PMX_reserved, PMX_reserved}},
    {28, PMX_PA28, {PMX_reserved, PMX_SFC_PORTA, PMX_reserved, PMX_reserved}},
    {36, PMX_PB04, {PMX_reserved, PMX_MII_PORTBDF, PMX_reserved, PMX_reserved}},
    {38, PMX_PB06, {PMX_GMAC_PORTB, PMX_reserved, PMX_reserved, PMX_reserved}},
    {39, PMX_PB07, {PMX_GMAC_PORTB, PMX_reserved, PMX_reserved, PMX_reserved}},
    {40, PMX_PB08, {PMX_GMAC_PORTB, PMX_MSC1_PORTB, PMX_reserved, PMX_reserved}},
    {41, PMX_PB09, {PMX_GMAC_PORTB, PMX_MSC1_PORTB, PMX_reserved, PMX_reserved}},
    {42, PMX_PB10, {PMX_GMAC_PORTB, PMX_MSC1_PORTB, PMX_reserved, PMX_reserved}},
    {43, PMX_PB11, {PMX_GMAC_PORTB, PMX_MSC1_PORTB, PMX_reserved, PMX_reserved}},
    {45, PMX_PB13, {PMX_GMAC_PORTB, PMX_MSC1_PORTB, PMX_reserved, PMX_reserved}},
    {46, PMX_PB14, {PMX_GMAC_PORTB, PMX_MSC1_PORTB, PMX_reserved, PMX_reserved}},
    {47, PMX_PB15, {PMX_GMAC_PORTB, PMX_SSI0_PORTB, PMX_SFC_PORTA_QUAD, PMX_reserved}},
    {48, PMX_PB16, {PMX_GMAC_PORTB, PMX_SSI0_PORTB, PMX_SFC_PORTA_QUAD, PMX_reserved}},
    {49, PMX_PB17, {PMX_reserved, PMX_SSI0_PORTB, PMX_UART2_PORTB, PMX_reserved}},
    {50, PMX_PB18, {PMX_reserved, PMX_SSI0_PORTB, PMX_UART2_PORTB, PMX_reserved}},
    {51, PMX_PB19, {PMX_UART0_PORTB, PMX_reserved, PMX_reserved, PMX_reserved}},
    {52, PMX_PB20, {PMX_UART0_PORTB_FC, PMX_reserved, PMX_I2C2_PORTB, PMX_reserved}},
    {53, PMX_PB21, {PMX_UART0_PORTB_FC, PMX_reserved, PMX_I2C2_PORTB, PMX_reserved}},
    {54, PMX_PB22, {PMX_UART0_PORTB, PMX_reserved, PMX_reserved, PMX_reserved}},
    {55, PMX_PB23, {PMX_UART1_PORTB, PMX_reserved, PMX_reserved, PMX_reserved}},
    {56, PMX_PB24, {PMX_UART1_PORTB, PMX_reserved, PMX_reserved, PMX_reserved}},
    {57, PMX_PB25, {PMX_I2C1_PORTB, PMX_reserved, PMX_UART2_PORTB_FC, PMX_reserved}},
    {58, PMX_PB26, {PMX_I2C1_PORTB, PMX_reserved, PMX_UART2_PORTB_FC, PMX_reserved}},
    {59, PMX_PB27, {PMX_OTG_DRVVUS, PMX_reserved, PMX_SSI0_PORTB, PMX_reserved}},
    {60, PMX_PB28, {PMX_reserved, PMX_reserved, PMX_SSI0_PORTB, PMX_DMIC_PORTC}},
    {61, PMX_PB29, {PMX_reserved, PMX_reserved, PMX_SSI0_PORTB, PMX_DMIC_PORTC}},
    {62, PMX_PB30, {PMX_reserved, PMX_reserved, PMX_SSI0_PORTB, PMX_DMIC_PORTC}},
    {63, PMX_PB31, {PMX_reserved, PMX_reserved, PMX_SSI0_PORTB_3, PMX_reserved}},
    {66, PMX_PC02, {PMX_MSC1_PORTC, PMX_reserved, PMX_reserved, PMX_reserved}},
    {67, PMX_PC03, {PMX_MSC1_PORTC, PMX_reserved, PMX_reserved, PMX_reserved}},
    {68, PMX_PC04, {PMX_MSC1_PORTC, PMX_reserved, PMX_reserved, PMX_reserved}},
    {69, PMX_PC05, {PMX_MSC1_PORTC, PMX_reserved, PMX_reserved, PMX_reserved}},
    {70, PMX_PC06, {PMX_MSC1_PORTC, PMX_reserved, PMX_reserved, PMX_reserved}},
    {71, PMX_PC07, {PMX_MSC1_PORTC, PMX_reserved, PMX_reserved, PMX_reserved}},
    {72, PMX_PC08, {PMX_reserved, PMX_reserved, PMX_reserved, PMX_I2C1_PORTC}},
    {73, PMX_PC09, {PMX_reserved, PMX_reserved, PMX_reserved, PMX_I2C1_PORTC}},
    {75, PMX_PC11, {PMX_reserved, PMX_reserved, PMX_UART2_PORTC_FC, PMX_reserved}},
    {76, PMX_PC12, {PMX_reserved, PMX_reserved, PMX_UART2_PORTC_FC, PMX_reserved}},
    {77, PMX_PC13, {PMX_reserved, PMX_reserved, PMX_UART2_PORTC, PMX_reserved}},
    {78, PMX_PC14, {PMX_reserved, PMX_reserved, PMX_UART2_PORTC, PMX_reserved}},
    {82, PMX_PC18, {PMX_I2S_PORTC, PMX_reserved, PMX_reserved, PMX_reserved}},
    {83, PMX_PC19, {PMX_I2S_PORTC, PMX_reserved, PMX_reserved, PMX_reserved}},
    {84, PMX_PC20, {PMX_I2S_PORTC, PMX_reserved, PMX_reserved, PMX_reserved}},
    {85, PMX_PC21, {PMX_I2S_PORTC, PMX_reserved, PMX_reserved, PMX_reserved}},
    {86, PMX_PC22, {PMX_I2S_PORTC, PMX_reserved, PMX_reserved, PMX_reserved}},
    {87, PMX_PC23, {PMX_I2S_PORTC, PMX_reserved, PMX_reserved, PMX_reserved}},
    {88, PMX_PC24, {PMX_I2S_PORTC, PMX_reserved, PMX_reserved, PMX_reserved}},
};

static const ingenic_soc_t T23_padmux = {T23_pads, 67};

/* T40: 100 pads named, of 128 in the SoC's 4 ports. A pad no source
 * names is not here at all, which is a different answer from one
 * whose four functions are all unused.
 *
 * From the pinctrl devicetree, one node per routing: a port, a
 * pin range and a function code, named for the device and the
 * port it lands on. Device-level, not per wire.
 *   84b81752457d1a6c  t40-pinctrl.dtsi
 */
static const ingenic_pad_t T40_pads[] = {
    {0, PMX_PA00, {PMX_VIC_PA, PMX_reserved, PMX_reserved, PMX_reserved}},
    {1, PMX_PA01, {PMX_VIC_PA, PMX_reserved, PMX_reserved, PMX_reserved}},
    {2, PMX_PA02, {PMX_VIC_PA, PMX_reserved, PMX_UART3_PA, PMX_reserved}},
    {3, PMX_PA03, {PMX_VIC_PA, PMX_reserved, PMX_UART3_PA, PMX_reserved}},
    {4, PMX_PA04, {PMX_VIC_PA, PMX_reserved, PMX_reserved, PMX_reserved}},
    {5, PMX_PA05, {PMX_VIC_PA, PMX_reserved, PMX_reserved, PMX_reserved}},
    {6, PMX_PA06, {PMX_VIC_PA, PMX_reserved, PMX_UART2_PA, PMX_reserved}},
    {7, PMX_PA07, {PMX_VIC_PA, PMX_reserved, PMX_UART2_PA, PMX_reserved}},
    {8, PMX_PA08, {PMX_VIC_PA, PMX_reserved, PMX_reserved, PMX_reserved}},
    {9, PMX_PA09, {PMX_VIC_PA, PMX_reserved, PMX_reserved, PMX_reserved}},
    {10, PMX_PA10, {PMX_VIC_PA, PMX_reserved, PMX_UART0_PA, PMX_reserved}},
    {11, PMX_PA11, {PMX_VIC_PA, PMX_reserved, PMX_UART0_PA, PMX_reserved}},
    {12, PMX_PA12, {PMX_VIC_PA, PMX_I2C0_PA, PMX_reserved, PMX_reserved}},
    {13, PMX_PA13, {PMX_VIC_PA, PMX_I2C0_PA, PMX_reserved, PMX_reserved}},
    {14, PMX_PA14, {PMX_VIC_PA, PMX_reserved, PMX_reserved, PMX_reserved}},
    {17, PMX_PA17, {PMX_reserved, PMX_I2C1_PA, PMX_UART1_PA, PMX_reserved}},
    {18, PMX_PA18, {PMX_reserved, PMX_I2C1_PA, PMX_UART1_PA, PMX_reserved}},
    {21, PMX_PA21, {PMX_reserved, PMX_reserved, PMX_I2C3_PA, PMX_reserved}},
    {22, PMX_PA22, {PMX_reserved, PMX_reserved, PMX_I2C3_PA, PMX_reserved}},
    {23, PMX_PA23, {PMX_reserved, PMX_SFC_PA, PMX_reserved, PMX_reserved}},
    {24, PMX_PA24, {PMX_reserved, PMX_SFC_PA, PMX_reserved, PMX_reserved}},
    {25, PMX_PA25, {PMX_reserved, PMX_SFC_PA, PMX_reserved, PMX_reserved}},
    {26, PMX_PA26, {PMX_reserved, PMX_SFC_PA, PMX_reserved, PMX_reserved}},
    {27, PMX_PA27, {PMX_reserved, PMX_SFC_PA, PMX_reserved, PMX_reserved}},
    {28, PMX_PA28, {PMX_reserved, PMX_SFC_PA, PMX_reserved, PMX_reserved}},
    {32, PMX_PB00, {PMX_MSC0_PB, PMX_reserved, PMX_reserved, PMX_reserved}},
    {33, PMX_PB01, {PMX_MSC0_PB, PMX_reserved, PMX_reserved, PMX_reserved}},
    {34, PMX_PB02, {PMX_MSC0_PB, PMX_reserved, PMX_reserved, PMX_reserved}},
    {35, PMX_PB03, {PMX_MSC0_PB, PMX_reserved, PMX_reserved, PMX_reserved}},
    {36, PMX_PB04, {PMX_MSC0_PB, PMX_reserved, PMX_reserved, PMX_reserved}},
    {37, PMX_PB05, {PMX_MSC0_PB, PMX_reserved, PMX_reserved, PMX_reserved}},
    {39, PMX_PB07, {PMX_MAC0_RMII_P1, PMX_reserved, PMX_reserved, PMX_reserved}},
    {47, PMX_PB15, {PMX_MAC0_RMII_P0_NORMAL, PMX_reserved, PMX_reserved, PMX_reserved}},
    {48, PMX_PB16, {PMX_MAC0_RMII_P0_NORMAL, PMX_reserved, PMX_reserved, PMX_reserved}},
    {49, PMX_PB17, {PMX_MSC1_PB, PMX_I2C1_PB, PMX_reserved, PMX_reserved}},
    {50, PMX_PB18, {PMX_MSC1_PB, PMX_I2C1_PB, PMX_reserved, PMX_reserved}},
    {51, PMX_PB19, {PMX_MSC1_PB, PMX_reserved, PMX_reserved, PMX_reserved}},
    {52, PMX_PB20, {PMX_MSC1_PB, PMX_I2C3_PB1, PMX_reserved, PMX_reserved}},
    {53, PMX_PB21, {PMX_MSC1_PB, PMX_I2C3_PB1, PMX_reserved, PMX_reserved}},
    {54, PMX_PB22, {PMX_MSC1_PB, PMX_reserved, PMX_reserved, PMX_reserved}},
    {55, PMX_PB23, {PMX_UART1_PB, PMX_reserved, PMX_reserved, PMX_reserved}},
    {56, PMX_PB24, {PMX_UART1_PB, PMX_reserved, PMX_reserved, PMX_reserved}},
    {57, PMX_PB25, {PMX_I2C2_PB, PMX_reserved, PMX_SPI1_PB, PMX_reserved}},
    {58, PMX_PB26, {PMX_I2C2_PB, PMX_reserved, PMX_SPI1_PB, PMX_reserved}},
    {59, PMX_PB27, {PMX_reserved, PMX_reserved, PMX_SPI1_PB, PMX_reserved}},
    {60, PMX_PB28, {PMX_I2C3_PB, PMX_UART2_PB, PMX_SPI1_PB, PMX_reserved}},
    {61, PMX_PB29, {PMX_I2C3_PB, PMX_UART2_PB, PMX_SPI1_PB, PMX_reserved}},
    {62, PMX_PB30, {PMX_reserved, PMX_reserved, PMX_SPI1_PB, PMX_reserved}},
    {66, PMX_PC02, {PMX_UART0_PC, PMX_SPI0_PC, PMX_PWM0_PC, PMX_reserved}},
    {67, PMX_PC03, {PMX_UART0_PC, PMX_SPI0_PC, PMX_PWM1_PC, PMX_reserved}},
    {68, PMX_PC04, {PMX_UART0_PC, PMX_SPI0_PC, PMX_PWM2_PC, PMX_reserved}},
    {69, PMX_PC05, {PMX_UART0_PC, PMX_SPI0_PC, PMX_PWM3_PC, PMX_reserved}},
    {70, PMX_PC06, {PMX_UART3_PC, PMX_reserved, PMX_PWM4_PC, PMX_reserved}},
    {71, PMX_PC07, {PMX_UART3_PC, PMX_reserved, PMX_PWM5_PC, PMX_reserved}},
    {72, PMX_PC08, {PMX_MSC1_PC, PMX_reserved, PMX_SPI1_PC, PMX_reserved}},
    {73, PMX_PC09, {PMX_MSC1_PC, PMX_reserved, PMX_SPI1_PC, PMX_reserved}},
    {74, PMX_PC10, {PMX_MSC1_PC, PMX_reserved, PMX_SPI1_PC, PMX_reserved}},
    {75, PMX_PC11, {PMX_MSC1_PC, PMX_reserved, PMX_SPI1_PC, PMX_reserved}},
    {76, PMX_PC12, {PMX_MSC1_PC, PMX_reserved, PMX_SPI1_PC, PMX_reserved}},
    {77, PMX_PC13, {PMX_MSC1_PC, PMX_reserved, PMX_SPI1_PC, PMX_reserved}},
    {78, PMX_PC14, {PMX_reserved, PMX_UART0_PC1, PMX_I2C2_PC, PMX_reserved}},
    {79, PMX_PC15, {PMX_reserved, PMX_UART0_PC1, PMX_I2C2_PC, PMX_reserved}},
    {80, PMX_PC16, {PMX_reserved, PMX_reserved, PMX_I2C0_PC, PMX_reserved}},
    {81, PMX_PC17, {PMX_reserved, PMX_reserved, PMX_I2C0_PC, PMX_reserved}},
    {82, PMX_PC18, {PMX_UART2_PC, PMX_reserved, PMX_reserved, PMX_reserved}},
    {83, PMX_PC19, {PMX_UART2_PC, PMX_reserved, PMX_reserved, PMX_reserved}},
    {88, PMX_PC24, {PMX_reserved, PMX_reserved, PMX_DMIC_PC, PMX_reserved}},
    {89, PMX_PC25, {PMX_reserved, PMX_reserved, PMX_DMIC_PC, PMX_reserved}},
    {90, PMX_PC26, {PMX_reserved, PMX_reserved, PMX_DMIC_PC, PMX_reserved}},
    {93, PMX_PC29, {PMX_reserved, PMX_CIM2_VIC_MCLK_PC, PMX_reserved, PMX_reserved}},
    {94, PMX_PC30, {PMX_reserved, PMX_CIM1_VIC_MCLK_PC, PMX_reserved, PMX_reserved}},
    {95, PMX_PC31, {PMX_reserved, PMX_CIM0_VIC_MCLK_PC, PMX_reserved, PMX_reserved}},
    {96, PMX_PD00, {PMX_TFT_LCD_PD, PMX_reserved, PMX_SMART_LCD_PD, PMX_reserved}},
    {97, PMX_PD01, {PMX_TFT_LCD_PD, PMX_reserved, PMX_SMART_LCD_PD, PMX_reserved}},
    {98, PMX_PD02, {PMX_TFT_LCD_PD, PMX_reserved, PMX_SMART_LCD_PD, PMX_reserved}},
    {99, PMX_PD03, {PMX_TFT_LCD_PD, PMX_reserved, PMX_SMART_LCD_PD, PMX_reserved}},
    {100, PMX_PD04, {PMX_TFT_LCD_PD, PMX_reserved, PMX_SMART_LCD_PD, PMX_reserved}},
    {101, PMX_PD05, {PMX_TFT_LCD_PD, PMX_reserved, PMX_SMART_LCD_PD, PMX_reserved}},
    {102, PMX_PD06, {PMX_TFT_LCD_PD, PMX_reserved, PMX_SMART_LCD_PD, PMX_reserved}},
    {103, PMX_PD07, {PMX_TFT_LCD_PD, PMX_reserved, PMX_SMART_LCD_PD, PMX_reserved}},
    {104, PMX_PD08, {PMX_TFT_LCD_PD, PMX_reserved, PMX_SMART_LCD_PD, PMX_reserved}},
    {105, PMX_PD09, {PMX_TFT_LCD_PD, PMX_reserved, PMX_reserved, PMX_reserved}},
    {106, PMX_PD10, {PMX_TFT_LCD_PD, PMX_reserved, PMX_reserved, PMX_reserved}},
    {107, PMX_PD11, {PMX_TFT_LCD_PD, PMX_reserved, PMX_reserved, PMX_reserved}},
    {108, PMX_PD12, {PMX_TFT_LCD_PD, PMX_reserved, PMX_reserved, PMX_reserved}},
    {109, PMX_PD13, {PMX_TFT_LCD_PD, PMX_reserved, PMX_reserved, PMX_reserved}},
    {110, PMX_PD14, {PMX_TFT_LCD_PD, PMX_reserved, PMX_reserved, PMX_reserved}},
    {111, PMX_PD15, {PMX_TFT_LCD_PD, PMX_reserved, PMX_reserved, PMX_reserved}},
    {112, PMX_PD16, {PMX_TFT_LCD_PD, PMX_reserved, PMX_reserved, PMX_reserved}},
    {113, PMX_PD17, {PMX_TFT_LCD_PD, PMX_reserved, PMX_reserved, PMX_reserved}},
    {114, PMX_PD18, {PMX_TFT_LCD_PD, PMX_reserved, PMX_reserved, PMX_reserved}},
    {115, PMX_PD19, {PMX_TFT_LCD_PD, PMX_reserved, PMX_reserved, PMX_reserved}},
    {116, PMX_PD20, {PMX_TFT_LCD_PD, PMX_reserved, PMX_reserved, PMX_reserved}},
    {117, PMX_PD21, {PMX_TFT_LCD_PD, PMX_reserved, PMX_reserved, PMX_reserved}},
    {118, PMX_PD22, {PMX_UART3_PD, PMX_reserved, PMX_PWM6_PD, PMX_reserved}},
    {119, PMX_PD23, {PMX_UART3_PD, PMX_reserved, PMX_PWM7_PD, PMX_reserved}},
    {120, PMX_PD24, {PMX_UART3_PD, PMX_reserved, PMX_reserved, PMX_reserved}},
    {121, PMX_PD25, {PMX_UART3_PD, PMX_reserved, PMX_reserved, PMX_reserved}},
    {122, PMX_PD26, {PMX_I2C1_PD, PMX_reserved, PMX_reserved, PMX_reserved}},
    {123, PMX_PD27, {PMX_I2C1_PD, PMX_reserved, PMX_reserved, PMX_reserved}},
};

static const ingenic_soc_t T40_padmux = {T40_pads, 100};

#endif /* HAL_INGENIC_PADMUX_H */
