/* Generated by tools/gen_novatek_padmux.py -- do not edit.
 *
 * What the vendor's pinmux_config_*() functions do to each pad of the
 * NA51089, found by running them: see the generator for how, and
 * src/hal/novatek_padmux.c for how the table is read. 96550 vendor states
 * were replayed against it; in 19185 of them two claims hold at once and the
 * table carries the one the vendor code meant, and 478 leave a pad cleared
 * with its field moved elsewhere, which reads as unnamed.
 *
 * Regenerate with:
 *   tools/gen_novatek_padmux.py --sdk <na51089 SDK root>
 */

#ifndef HAL_NOVATEK_PADMUX_H
#define HAL_NOVATEK_PADMUX_H

#include "hal/novatek_padmux_types.h"

/* Every pad the package bonds out, by Linux GPIO number. */
static const novatek_pad_t NA51089_pads[] = {
    {0, PMX_C_GPIO0},
    {1, PMX_C_GPIO1},
    {2, PMX_C_GPIO2},
    {3, PMX_C_GPIO3},
    {4, PMX_C_GPIO4},
    {5, PMX_C_GPIO5},
    {6, PMX_C_GPIO6},
    {7, PMX_C_GPIO7},
    {8, PMX_C_GPIO8},
    {9, PMX_C_GPIO9},
    {10, PMX_C_GPIO10},
    {11, PMX_C_GPIO11},
    {12, PMX_C_GPIO12},
    {13, PMX_C_GPIO13},
    {14, PMX_C_GPIO14},
    {15, PMX_C_GPIO15},
    {16, PMX_C_GPIO16},
    {17, PMX_C_GPIO17},
    {18, PMX_C_GPIO18},
    {19, PMX_C_GPIO19},
    {20, PMX_C_GPIO20},
    {21, PMX_C_GPIO21},
    {22, PMX_C_GPIO22},
    {32, PMX_P_GPIO0},
    {33, PMX_P_GPIO1},
    {34, PMX_P_GPIO2},
    {35, PMX_P_GPIO3},
    {36, PMX_P_GPIO4},
    {37, PMX_P_GPIO5},
    {38, PMX_P_GPIO6},
    {39, PMX_P_GPIO7},
    {40, PMX_P_GPIO8},
    {41, PMX_P_GPIO9},
    {42, PMX_P_GPIO10},
    {43, PMX_P_GPIO11},
    {44, PMX_P_GPIO12},
    {45, PMX_P_GPIO13},
    {46, PMX_P_GPIO14},
    {47, PMX_P_GPIO15},
    {48, PMX_P_GPIO16},
    {49, PMX_P_GPIO17},
    {50, PMX_P_GPIO18},
    {51, PMX_P_GPIO19},
    {52, PMX_P_GPIO20},
    {53, PMX_P_GPIO21},
    {54, PMX_P_GPIO22},
    {55, PMX_P_GPIO23},
    {56, PMX_P_GPIO24},
    {57, PMX_P_GPIO25},
    {64, PMX_S_GPIO0},
    {65, PMX_S_GPIO1},
    {66, PMX_S_GPIO2},
    {67, PMX_S_GPIO3},
    {68, PMX_S_GPIO4},
    {69, PMX_S_GPIO5},
    {70, PMX_S_GPIO6},
    {71, PMX_S_GPIO7},
    {72, PMX_S_GPIO8},
    {96, PMX_L_GPIO0},
    {97, PMX_L_GPIO1},
    {98, PMX_L_GPIO2},
    {99, PMX_L_GPIO3},
    {100, PMX_L_GPIO4},
    {101, PMX_L_GPIO5},
    {102, PMX_L_GPIO6},
    {103, PMX_L_GPIO7},
    {104, PMX_L_GPIO8},
    {105, PMX_L_GPIO9},
    {128, PMX_D_GPIO0},
    {129, PMX_D_GPIO1},
    {130, PMX_D_GPIO2},
    {131, PMX_D_GPIO3},
    {132, PMX_D_GPIO4},
    {133, PMX_D_GPIO5},
    {134, PMX_D_GPIO6},
    {135, PMX_D_GPIO7},
    {160, PMX_H_GPIO0},
    {161, PMX_H_GPIO1},
    {162, PMX_H_GPIO2},
    {163, PMX_H_GPIO3},
    {164, PMX_H_GPIO4},
    {165, PMX_H_GPIO5},
    {166, PMX_H_GPIO6},
    {167, PMX_H_GPIO7},
    {168, PMX_H_GPIO8},
    {169, PMX_H_GPIO9},
    {170, PMX_H_GPIO10},
    {171, PMX_H_GPIO11},
    {192, PMX_A_GPIO0},
    {193, PMX_A_GPIO1},
    {194, PMX_A_GPIO2},
    {224, PMX_DSI_GPIO0},
    {225, PMX_DSI_GPIO1},
    {226, PMX_DSI_GPIO2},
    {227, PMX_DSI_GPIO3},
    {228, PMX_DSI_GPIO4},
    {229, PMX_DSI_GPIO5},
    {230, PMX_DSI_GPIO6},
    {231, PMX_DSI_GPIO7},
    {232, PMX_DSI_GPIO8},
    {233, PMX_DSI_GPIO9},
    {234, PMX_DSI_GPIO10},
};

/* TOP register offset, field shift, width, value. */
static const novatek_cond_t NA51089_conds[] = {
    {0x04, 17, 1, 1},
    {0x04, 17, 1, 1},
    {0x04, 31, 1, 1},
    {0x1C, 0, 3, 4},
    {0x1C, 3, 3, 4},
    {0x1C, 6, 3, 4},
    {0x1C, 9, 3, 4},
    {0x18, 10, 2, 2},
    {0x18, 5, 1, 1},
    {0x18, 6, 1, 1},
    {0x18, 30, 2, 3},
    {0x14, 6, 2, 2},
    {0x18, 2, 2, 2},
    {0x1C, 12, 3, 2},
    {0x04, 14, 1, 1},
    {0x14, 12, 2, 2},
    {0x18, 0, 2, 2},
    {0x1C, 15, 3, 2},
    {0x24, 2, 2, 2},
    {0x24, 8, 2, 1},
    {0x1C, 0, 3, 2},
    {0x14, 12, 2, 2},
    {0x14, 18, 1, 1},
    {0x24, 2, 2, 2},
    {0x24, 8, 2, 2},
    {0x1C, 3, 3, 2},
    {0x18, 7, 2, 2},
    {0x18, 7, 2, 2},
    {0x1C, 24, 2, 2},
    {0x14, 12, 2, 2},
    {0x14, 14, 2, 2},
    {0x1C, 6, 3, 2},
    {0x24, 2, 2, 2},
    {0x1C, 9, 3, 2},
    {0x14, 4, 2, 2},
    {0x1C, 18, 3, 2},
    {0x04, 18, 2, 1},
    {0x14, 8, 2, 1},
    {0x1C, 21, 3, 2},
    {0x24, 4, 3, 2},
    {0x24, 10, 2, 1},
    {0x18, 16, 3, 2},
    {0x14, 8, 2, 1},
    {0x14, 16, 1, 1},
    {0x24, 4, 3, 2},
    {0x24, 10, 2, 2},
    {0x18, 19, 3, 2},
    {0x18, 22, 3, 2},
    {0x24, 4, 3, 2},
    {0x18, 25, 3, 2},
    {0x14, 30, 2, 2},
    {0x1C, 0, 3, 1},
    {0x0C, 4, 2, 1},
    {0x0C, 4, 2, 2},
    {0x0C, 0, 3, 2},
    {0x0C, 0, 3, 4},
    {0x14, 10, 2, 2},
    {0x24, 2, 2, 3},
    {0x1C, 3, 3, 1},
    {0x24, 2, 2, 3},
    {0x24, 8, 2, 1},
    {0x24, 2, 2, 3},
    {0x24, 8, 2, 2},
    {0x1C, 6, 3, 1},
    {0x14, 10, 2, 2},
    {0x14, 17, 1, 1},
    {0x1C, 9, 3, 1},
    {0x1C, 12, 3, 1},
    {0x14, 12, 2, 3},
    {0x24, 4, 3, 3},
    {0x1C, 15, 3, 1},
    {0x24, 4, 3, 3},
    {0x24, 10, 2, 1},
    {0x24, 4, 3, 3},
    {0x24, 10, 2, 2},
    {0x1C, 18, 3, 1},
    {0x14, 30, 2, 2},
    {0x18, 28, 1, 1},
    {0x14, 12, 2, 3},
    {0x14, 18, 1, 1},
    {0x1C, 21, 3, 1},
    {0x14, 26, 1, 1},
    {0x14, 12, 2, 3},
    {0x14, 14, 2, 3},
    {0x18, 2, 2, 1},
    {0x18, 16, 3, 1},
    {0x14, 2, 2, 2},
    {0x14, 30, 2, 2},
    {0x14, 2, 2, 2},
    {0x18, 0, 2, 1},
    {0x18, 19, 3, 1},
    {0x18, 22, 3, 1},
    {0x14, 24, 2, 1},
    {0x18, 25, 3, 1},
    {0x0C, 4, 2, 1},
    {0x0C, 16, 1, 1},
    {0x14, 12, 2, 1},
    {0x14, 14, 2, 1},
    {0x1C, 26, 2, 1},
    {0x0C, 16, 1, 1},
    {0x18, 5, 1, 1},
    {0x18, 6, 1, 1},
    {0x18, 30, 2, 1},
    {0x1C, 30, 2, 1},
    {0x18, 7, 2, 1},
    {0x14, 24, 2, 2},
    {0x14, 12, 2, 1},
    {0x24, 2, 2, 1},
    {0x18, 7, 2, 1},
    {0x1C, 24, 2, 1},
    {0x1C, 26, 2, 2},
    {0x24, 2, 2, 1},
    {0x24, 8, 2, 1},
    {0x24, 2, 2, 1},
    {0x24, 8, 2, 2},
    {0x1C, 28, 2, 2},
    {0x18, 9, 1, 1},
    {0x14, 12, 2, 1},
    {0x14, 18, 1, 1},
    {0x1C, 30, 2, 2},
    {0x0C, 18, 2, 1},
    {0x14, 6, 2, 1},
    {0x18, 10, 2, 1},
    {0x24, 0, 1, 1},
    {0x04, 18, 2, 2},
    {0x0C, 8, 2, 1},
    {0x24, 4, 3, 4},
    {0x0C, 0, 3, 4},
    {0x0C, 6, 2, 0},
    {0x0C, 12, 2, 1},
    {0x0C, 0, 3, 4},
    {0x0C, 6, 2, 0},
    {0x0C, 0, 3, 1},
    {0x0C, 12, 2, 1},
    {0x0C, 0, 3, 3},
    {0x0C, 12, 2, 1},
    {0x1C, 0, 3, 3},
    {0x0C, 0, 3, 1},
    {0x0C, 0, 3, 3},
    {0x0C, 12, 2, 1},
    {0x1C, 3, 3, 3},
    {0x0C, 10, 2, 1},
    {0x1C, 6, 3, 3},
    {0x14, 22, 1, 1},
    {0x14, 4, 2, 1},
    {0x1C, 9, 3, 3},
    {0x0C, 14, 2, 1},
    {0x24, 4, 3, 5},
    {0x14, 8, 2, 2},
    {0x14, 16, 1, 1},
    {0x1C, 12, 3, 3},
    {0x1C, 15, 3, 3},
    {0x14, 20, 1, 1},
    {0x14, 8, 2, 2},
    {0x14, 0, 2, 1},
    {0x1C, 18, 3, 3},
    {0x1C, 21, 3, 3},
    {0x0C, 12, 2, 2},
    {0x18, 25, 3, 5},
    {0x1C, 28, 2, 1},
    {0x0C, 18, 2, 2},
    {0x18, 13, 2, 1},
    {0x1C, 12, 3, 4},
    {0x14, 24, 2, 3},
    {0x0C, 18, 2, 3},
    {0x1C, 15, 3, 4},
    {0x18, 10, 2, 3},
    {0x18, 13, 2, 2},
    {0x1C, 18, 3, 4},
    {0x1C, 21, 3, 4},
    {0x18, 25, 3, 4},
    {0x0C, 0, 3, 4},
    {0x0C, 6, 2, 1},
    {0x18, 16, 3, 3},
    {0x18, 19, 3, 3},
    {0x0C, 10, 2, 2},
    {0x18, 22, 3, 3},
    {0x14, 0, 2, 2},
    {0x18, 25, 3, 3},
    {0x0C, 0, 3, 4},
    {0x0C, 6, 2, 1},
    {0x0C, 8, 2, 2},
    {0x0C, 0, 3, 1},
    {0x0C, 8, 2, 2},
    {0x0C, 0, 3, 3},
    {0x0C, 8, 2, 2},
    {0x0C, 8, 2, 2},
    {0x14, 2, 2, 1},
    {0x1C, 0, 3, 5},
    {0x24, 4, 3, 1},
    {0x1C, 3, 3, 5},
    {0x24, 4, 3, 1},
    {0x24, 10, 2, 1},
    {0x24, 4, 3, 1},
    {0x24, 10, 2, 2},
    {0x14, 30, 2, 1},
    {0x1C, 6, 3, 5},
    {0x04, 18, 2, 3},
    {0x1C, 9, 3, 5},
    {0x1C, 12, 3, 5},
    {0x14, 10, 2, 1},
    {0x1C, 15, 3, 5},
    {0x1C, 18, 3, 5},
    {0x14, 10, 2, 1},
    {0x14, 17, 1, 1},
    {0x1C, 21, 3, 5},
    {0x18, 5, 1, 1},
    {0x18, 6, 1, 1},
    {0x18, 30, 2, 2},
    {0x14, 6, 2, 3},
    {0x18, 16, 3, 5},
    {0x14, 2, 2, 1},
    {0x14, 30, 2, 1},
    {0x18, 19, 3, 5},
    {0x18, 28, 1, 1},
    {0x18, 22, 3, 5},
};

/* Per pad, most conditions first: the first claim that holds
 * is what the pad carries. {pad, flags, name, first
 * condition, how many}. */
static const novatek_claim_t NA51089_claims[] = {
    {0, 0, PMX_SDIO3_D0, 0, 1}, /* C_GPIO0 */
    {0, 0, PMX_FSPI_DO, 1, 0}, /* C_GPIO0 */
    {1, 0, PMX_SDIO3_D1, 0, 1}, /* C_GPIO1 */
    {1, 0, PMX_FSPI_DI, 1, 0}, /* C_GPIO1 */
    {2, 0, PMX_SDIO3_D2, 0, 1}, /* C_GPIO2 */
    {2, 0, PMX_FSPI_WP, 1, 0}, /* C_GPIO2 */
    {3, 0, PMX_SDIO3_D3, 0, 1}, /* C_GPIO3 */
    {3, 0, PMX_FSPI_HOLD, 1, 0}, /* C_GPIO3 */
    {4, 0, PMX_SDIO3_D4, 1, 2}, /* C_GPIO4 */
    {4, 0, PMX_PWM0_4, 3, 1}, /* C_GPIO4 */
    {5, 0, PMX_SDIO3_D5, 1, 2}, /* C_GPIO5 */
    {5, 0, PMX_PWM1_4, 4, 1}, /* C_GPIO5 */
    {6, 0, PMX_SDIO3_D6, 1, 2}, /* C_GPIO6 */
    {6, 0, PMX_PWM2_4, 5, 1}, /* C_GPIO6 */
    {7, 0, PMX_SDIO3_D7, 1, 2}, /* C_GPIO7 */
    {7, 0, PMX_PWM3_4, 6, 1}, /* C_GPIO7 */
    {8, 0, PMX_SDIO3_CLK, 0, 1}, /* C_GPIO8 */
    {8, 0, PMX_FSPI_CLK, 1, 0}, /* C_GPIO8 */
    {9, 0, PMX_SDIO3_CMD, 0, 1}, /* C_GPIO9 */
    {9, 0, PMX_SP_CLK2_2, 7, 1}, /* C_GPIO9 */
    {10, 0, PMX_FSPI_CS, 1, 0}, /* C_GPIO10 */
    {11, 0, PMX_DMCLK_3, 8, 3}, /* C_GPIO11 */
    {11, 0, PMX_I2C3_2_SCL, 11, 1}, /* C_GPIO11 */
    {11, 0, PMX_I2S_MCLK_2, 12, 1}, /* C_GPIO11 */
    {11, 0, PMX_PWM4_2, 13, 1}, /* C_GPIO11 */
    {11, 0, PMX_SDIO_CLK, 14, 1}, /* C_GPIO11 */
    {11, 0, PMX_SPI3_2_CLK, 15, 1}, /* C_GPIO11 */
    {12, 0, PMX_DMDAT0_3, 8, 3}, /* C_GPIO12 */
    {12, 0, PMX_I2C3_2_SDA, 11, 1}, /* C_GPIO12 */
    {12, 0, PMX_I2S_BCLK_2, 16, 1}, /* C_GPIO12 */
    {12, 0, PMX_PWM5_2, 17, 1}, /* C_GPIO12 */
    {12, 0, PMX_SDIO_CMD, 14, 1}, /* C_GPIO12 */
    {12, 0, PMX_SPI3_2_DO, 15, 1}, /* C_GPIO12 */
    {13, 0, PMX_DMDAT1_3, 8, 3}, /* C_GPIO13 */
    {13, 0, PMX_UART2_2_CTS, 18, 2}, /* C_GPIO13 */
    {13, 0, PMX_I2S_SYNC_2, 16, 1}, /* C_GPIO13 */
    {13, 0, PMX_PWM0_2, 20, 1}, /* C_GPIO13 */
    {13, 0, PMX_SDIO_D0, 14, 1}, /* C_GPIO13 */
    {13, 0, PMX_SPI3_2_CS, 15, 1}, /* C_GPIO13 */
    {14, 0, PMX_SPI3_2_DI, 21, 2}, /* C_GPIO14 */
    {14, 0, PMX_UART2_2_RTS, 18, 2}, /* C_GPIO14 */
    {14, 0, PMX_UART2_2_RTS, 23, 2}, /* C_GPIO14 */
    {14, 0, PMX_I2S_SDATAO_2, 16, 1}, /* C_GPIO14 */
    {14, 0, PMX_PWM1_2, 25, 1}, /* C_GPIO14 */
    {14, 0, PMX_REMOTE_IN_2, 26, 1}, /* C_GPIO14 */
    {14, 0, PMX_SDIO_D1, 14, 1}, /* C_GPIO14 */
    {15, 0, PMX_REMOTE_EXT, 27, 2}, /* C_GPIO15 */
    {15, 0, PMX_SPI_CH3_RDY, 29, 2}, /* C_GPIO15 */
    {15, 0, PMX_I2S_SDATAI_2, 16, 1}, /* C_GPIO15 */
    {15, 0, PMX_PWM2_2, 31, 1}, /* C_GPIO15 */
    {15, 0, PMX_SDIO_D2, 14, 1}, /* C_GPIO15 */
    {15, 0, PMX_UART2_2_TX, 32, 1}, /* C_GPIO15 */
    {16, 0, PMX_PWM3_2, 33, 1}, /* C_GPIO16 */
    {16, 0, PMX_SDIO_D3, 14, 1}, /* C_GPIO16 */
    {16, 0, PMX_UART2_2_RX, 32, 1}, /* C_GPIO16 */
    {17, 0, PMX_I2C2_2_SCL, 34, 1}, /* C_GPIO17 */
    {17, 0, PMX_PWM6_2, 35, 1}, /* C_GPIO17 */
    {17, 0, PMX_SDIO2_CLK, 36, 1}, /* C_GPIO17 */
    {17, 0, PMX_SPI_1_CLK, 37, 1}, /* C_GPIO17 */
    {18, 0, PMX_I2C2_2_SDA, 34, 1}, /* C_GPIO18 */
    {18, 0, PMX_PWM7_2, 38, 1}, /* C_GPIO18 */
    {18, 0, PMX_SDIO2_CMD, 36, 1}, /* C_GPIO18 */
    {18, 0, PMX_SPI_1_DO, 37, 1}, /* C_GPIO18 */
    {19, 0, PMX_UART3_2_CTS, 39, 2}, /* C_GPIO19 */
    {19, 0, PMX_PWM8_2, 41, 1}, /* C_GPIO19 */
    {19, 0, PMX_SDIO2_D0, 36, 1}, /* C_GPIO19 */
    {19, 0, PMX_SPI_1_CS, 37, 1}, /* C_GPIO19 */
    {20, 0, PMX_SPI_1_DI, 42, 2}, /* C_GPIO20 */
    {20, 0, PMX_UART3_2_RTS, 39, 2}, /* C_GPIO20 */
    {20, 0, PMX_UART3_2_RTS, 44, 2}, /* C_GPIO20 */
    {20, 0, PMX_PWM9_2, 46, 1}, /* C_GPIO20 */
    {20, 0, PMX_SDIO2_D1, 36, 1}, /* C_GPIO20 */
    {21, 0, PMX_PWM10_2, 47, 1}, /* C_GPIO21 */
    {21, 0, PMX_SDIO2_D2, 36, 1}, /* C_GPIO21 */
    {21, 0, PMX_UART3_2_TX, 48, 1}, /* C_GPIO21 */
    {22, 0, PMX_PWM11_2, 49, 1}, /* C_GPIO22 */
    {22, 0, PMX_SDIO2_D3, 36, 1}, /* C_GPIO22 */
    {22, 0, PMX_UART3_2_RX, 48, 1}, /* C_GPIO22 */
    {32, 0, PMX_ETH_RMII_2, 50, 1}, /* P_GPIO0 */
    {32, 0, PMX_PWM0_1, 51, 1}, /* P_GPIO0 */
    {32, NVT_UNGATED, PMX_SENSOR2_12BITS, 52, 1}, /* P_GPIO0 */
    {32, NVT_UNGATED, PMX_SENSOR2_CCIR8BITS, 53, 1}, /* P_GPIO0 */
    {32, NVT_UNGATED, PMX_SENSOR_12BITS_2ND, 54, 1}, /* P_GPIO0 */
    {32, 0, PMX_SENSOR_CCIR16BITS, 55, 1}, /* P_GPIO0 */
    {32, 0, PMX_SPI2_2_CS, 56, 1}, /* P_GPIO0 */
    {32, 0, PMX_UART2_3_TX, 57, 1}, /* P_GPIO0 */
    {33, 0, PMX_ETH_RMII_2, 50, 1}, /* P_GPIO1 */
    {33, 0, PMX_PWM1_1, 58, 1}, /* P_GPIO1 */
    {33, NVT_UNGATED, PMX_SENSOR2_12BITS, 52, 1}, /* P_GPIO1 */
    {33, NVT_UNGATED, PMX_SENSOR2_CCIR8BITS, 53, 1}, /* P_GPIO1 */
    {33, NVT_UNGATED, PMX_SENSOR_12BITS_2ND, 54, 1}, /* P_GPIO1 */
    {33, 0, PMX_SENSOR_CCIR16BITS, 55, 1}, /* P_GPIO1 */
    {33, 0, PMX_SPI2_2_CLK, 56, 1}, /* P_GPIO1 */
    {33, 0, PMX_UART2_3_RX, 57, 1}, /* P_GPIO1 */
    {34, 0, PMX_UART2_3_RTS, 59, 2}, /* P_GPIO2 */
    {34, 0, PMX_UART2_3_RTS, 61, 2}, /* P_GPIO2 */
    {34, 0, PMX_ETH_RMII_2, 50, 1}, /* P_GPIO2 */
    {34, 0, PMX_PWM2_1, 63, 1}, /* P_GPIO2 */
    {34, NVT_UNGATED, PMX_SENSOR2_12BITS, 52, 1}, /* P_GPIO2 */
    {34, NVT_UNGATED, PMX_SENSOR2_CCIR8BITS, 53, 1}, /* P_GPIO2 */
    {34, NVT_UNGATED, PMX_SENSOR_12BITS_2ND, 54, 1}, /* P_GPIO2 */
    {34, 0, PMX_SENSOR_CCIR16BITS, 55, 1}, /* P_GPIO2 */
    {34, 0, PMX_SPI2_2_DO, 56, 1}, /* P_GPIO2 */
    {35, 0, PMX_SPI2_2_DI, 64, 2}, /* P_GPIO3 */
    {35, 0, PMX_UART2_3_CTS, 59, 2}, /* P_GPIO3 */
    {35, 0, PMX_ETH_RMII_2, 50, 1}, /* P_GPIO3 */
    {35, 0, PMX_PWM3_1, 66, 1}, /* P_GPIO3 */
    {35, NVT_UNGATED, PMX_SENSOR2_12BITS, 52, 1}, /* P_GPIO3 */
    {35, NVT_UNGATED, PMX_SENSOR2_CCIR8BITS, 53, 1}, /* P_GPIO3 */
    {35, NVT_UNGATED, PMX_SENSOR_12BITS_2ND, 54, 1}, /* P_GPIO3 */
    {35, 0, PMX_SENSOR_CCIR16BITS, 55, 1}, /* P_GPIO3 */
    {36, 0, PMX_ETH_RMII_2, 50, 1}, /* P_GPIO4 */
    {36, 0, PMX_PWM4_1, 67, 1}, /* P_GPIO4 */
    {36, NVT_UNGATED, PMX_SENSOR2_12BITS, 52, 1}, /* P_GPIO4 */
    {36, NVT_UNGATED, PMX_SENSOR2_CCIR8BITS, 53, 1}, /* P_GPIO4 */
    {36, NVT_UNGATED, PMX_SENSOR_12BITS_2ND, 54, 1}, /* P_GPIO4 */
    {36, 0, PMX_SENSOR_CCIR16BITS, 55, 1}, /* P_GPIO4 */
    {36, 0, PMX_SPI3_3_CS, 68, 1}, /* P_GPIO4 */
    {36, 0, PMX_UART3_3_TX, 69, 1}, /* P_GPIO4 */
    {37, 0, PMX_ETH_RMII_2, 50, 1}, /* P_GPIO5 */
    {37, 0, PMX_PWM5_1, 70, 1}, /* P_GPIO5 */
    {37, NVT_UNGATED, PMX_SENSOR2_12BITS, 52, 1}, /* P_GPIO5 */
    {37, NVT_UNGATED, PMX_SENSOR2_CCIR8BITS, 53, 1}, /* P_GPIO5 */
    {37, NVT_UNGATED, PMX_SENSOR_12BITS_2ND, 54, 1}, /* P_GPIO5 */
    {37, 0, PMX_SENSOR_CCIR16BITS, 55, 1}, /* P_GPIO5 */
    {37, 0, PMX_SPI3_3_CLK, 68, 1}, /* P_GPIO5 */
    {37, 0, PMX_UART3_3_RX, 69, 1}, /* P_GPIO5 */
    {38, 0, PMX_UART3_3_RTS, 71, 2}, /* P_GPIO6 */
    {38, 0, PMX_UART3_3_RTS, 73, 2}, /* P_GPIO6 */
    {38, 0, PMX_PWM6_1, 75, 1}, /* P_GPIO6 */
    {38, NVT_UNGATED, PMX_SENSOR2_12BITS, 52, 1}, /* P_GPIO6 */
    {38, NVT_UNGATED, PMX_SENSOR2_CCIR8BITS, 53, 1}, /* P_GPIO6 */
    {38, NVT_UNGATED, PMX_SENSOR_12BITS_2ND, 54, 1}, /* P_GPIO6 */
    {38, 0, PMX_SENSOR_CCIR16BITS, 55, 1}, /* P_GPIO6 */
    {38, 0, PMX_SPI3_3_DO, 68, 1}, /* P_GPIO6 */
    {39, 0, PMX_ETH_EXTPHYCLK, 76, 2}, /* P_GPIO7 */
    {39, 0, PMX_SPI3_3_DI, 78, 2}, /* P_GPIO7 */
    {39, 0, PMX_UART3_3_CTS, 71, 2}, /* P_GPIO7 */
    {39, 0, PMX_PWM7_1, 80, 1}, /* P_GPIO7 */
    {39, 0, PMX_SB4_CS, 81, 1}, /* P_GPIO7 */
    {39, NVT_UNGATED, PMX_SENSOR2_12BITS, 52, 1}, /* P_GPIO7 */
    {39, NVT_UNGATED, PMX_SENSOR2_CCIR8BITS, 53, 1}, /* P_GPIO7 */
    {39, NVT_UNGATED, PMX_SENSOR_12BITS_2ND, 54, 1}, /* P_GPIO7 */
    {39, 0, PMX_SENSOR_CCIR16BITS, 55, 1}, /* P_GPIO7 */
    {40, 0, PMX_SPI_CH3_RDY, 82, 2}, /* P_GPIO8 */
    {40, 0, PMX_ETH_RMII_2, 50, 1}, /* P_GPIO8 */
    {40, 0, PMX_I2S_MCLK_1, 84, 1}, /* P_GPIO8 */
    {40, 0, PMX_PWM8_1, 85, 1}, /* P_GPIO8 */
    {40, 0, PMX_SB4_CK, 81, 1}, /* P_GPIO8 */
    {40, NVT_UNGATED, PMX_SENSOR2_12BITS, 52, 1}, /* P_GPIO8 */
    {40, 0, PMX_SENSOR2_CCIR8BITS, 53, 1}, /* P_GPIO8 */
    {40, NVT_UNGATED, PMX_SENSOR_12BITS_2ND, 54, 1}, /* P_GPIO8 */
    {41, 0, PMX_ETH_MDIO_2, 86, 2}, /* P_GPIO9 */
    {41, 0, PMX_ETH_MDIO_2, 88, 1}, /* P_GPIO9 */
    {41, 0, PMX_I2S_BCLK_1, 89, 1}, /* P_GPIO9 */
    {41, 0, PMX_PWM9_1, 90, 1}, /* P_GPIO9 */
    {41, 0, PMX_SB4_DAT, 81, 1}, /* P_GPIO9 */
    {41, NVT_UNGATED, PMX_SENSOR2_12BITS, 52, 1}, /* P_GPIO9 */
    {41, 0, PMX_SENSOR2_CCIR8BITS, 53, 1}, /* P_GPIO9 */
    {41, NVT_UNGATED, PMX_SENSOR_12BITS_2ND, 54, 1}, /* P_GPIO9 */
    {42, 0, PMX_ETH_MDIO_2, 86, 2}, /* P_GPIO10 */
    {42, 0, PMX_ETH_MDIO_2, 88, 1}, /* P_GPIO10 */
    {42, 0, PMX_I2S_SYNC_1, 89, 1}, /* P_GPIO10 */
    {42, 0, PMX_PWM10_1, 91, 1}, /* P_GPIO10 */
    {42, 0, PMX_SB3_1_CS, 92, 1}, /* P_GPIO10 */
    {42, NVT_UNGATED, PMX_SENSOR2_12BITS, 52, 1}, /* P_GPIO10 */
    {42, 0, PMX_SENSOR2_CCIR8BITS, 53, 1}, /* P_GPIO10 */
    {42, NVT_UNGATED, PMX_SENSOR_12BITS_2ND, 54, 1}, /* P_GPIO10 */
    {43, 0, PMX_I2S_SDATAO_1, 89, 1}, /* P_GPIO11 */
    {43, 0, PMX_PWM11_1, 93, 1}, /* P_GPIO11 */
    {43, 0, PMX_SB3_1_CK, 92, 1}, /* P_GPIO11 */
    {43, NVT_UNGATED, PMX_SENSOR2_12BITS, 52, 1}, /* P_GPIO11 */
    {43, 0, PMX_SENSOR2_CCIR8BITS, 53, 1}, /* P_GPIO11 */
    {43, NVT_UNGATED, PMX_SENSOR_12BITS_2ND, 54, 1}, /* P_GPIO11 */
    {44, 0, PMX_SENSOR2_SN3_MCLK, 94, 2}, /* P_GPIO12 */
    {44, 0, PMX_SPI_CH3_RDY, 96, 2}, /* P_GPIO12 */
    {44, 0, PMX_I2S_SDATAI_1, 89, 1}, /* P_GPIO12 */
    {44, 0, PMX_PICNT_1, 98, 1}, /* P_GPIO12 */
    {44, 0, PMX_SB3_1_DAT, 92, 1}, /* P_GPIO12 */
    {44, 0, PMX_SENSOR2_12BITS, 52, 1}, /* P_GPIO12 */
    {44, 0, PMX_SENSOR2_SN3_MCLK, 99, 1}, /* P_GPIO12 */
    {44, 0, PMX_SENSOR_12BITS_2ND, 54, 1}, /* P_GPIO12 */
    {49, 0, PMX_DMDAT0_1, 100, 3}, /* P_GPIO17 */
    {49, 0, PMX_PICNT3_1, 103, 1}, /* P_GPIO17 */
    {49, 0, PMX_REMOTE_IN_1, 104, 1}, /* P_GPIO17 */
    {49, 0, PMX_SB3_2_CS, 105, 1}, /* P_GPIO17 */
    {49, 0, PMX_SPI3_1_CS, 106, 1}, /* P_GPIO17 */
    {49, 0, PMX_UART2_1_TX, 107, 1}, /* P_GPIO17 */
    {50, 0, PMX_DMDAT1_1, 100, 3}, /* P_GPIO18 */
    {50, 0, PMX_REMOTE_EXT, 108, 2}, /* P_GPIO18 */
    {50, 0, PMX_PICNT_2, 110, 1}, /* P_GPIO18 */
    {50, 0, PMX_SB3_2_CK, 105, 1}, /* P_GPIO18 */
    {50, 0, PMX_SPI3_1_CLK, 106, 1}, /* P_GPIO18 */
    {50, 0, PMX_UART2_1_RX, 107, 1}, /* P_GPIO18 */
    {51, 0, PMX_DMCLK_1, 100, 3}, /* P_GPIO19 */
    {51, 0, PMX_UART2_1_RTS, 111, 2}, /* P_GPIO19 */
    {51, 0, PMX_UART2_1_RTS, 113, 2}, /* P_GPIO19 */
    {51, 0, PMX_PICNT2_2, 115, 1}, /* P_GPIO19 */
    {51, 0, PMX_RTC_CLK, 116, 1}, /* P_GPIO19 */
    {51, 0, PMX_SB3_2_DAT, 105, 1}, /* P_GPIO19 */
    {51, 0, PMX_SPI3_1_DO, 106, 1}, /* P_GPIO19 */
    {52, 0, PMX_SPI3_1_DI, 117, 2}, /* P_GPIO20 */
    {52, 0, PMX_UART2_1_CTS, 111, 2}, /* P_GPIO20 */
    {52, 0, PMX_PICNT3_2, 119, 1}, /* P_GPIO20 */
    {52, 0, PMX_SP_CLK_1, 120, 1}, /* P_GPIO20 */
    {53, 0, PMX_I2C3_1_SDA, 121, 1}, /* P_GPIO21 */
    {53, 0, PMX_SP_CLK2_1, 122, 1}, /* P_GPIO21 */
    {54, 0, PMX_I2C3_1_SCL, 121, 1}, /* P_GPIO22 */
    {55, 0, PMX_UART_TX, 123, 1}, /* P_GPIO23 */
    {56, 0, PMX_UART_RX, 123, 1}, /* P_GPIO24 */
    {64, 0, PMX_SDIO2_CLK, 124, 1}, /* S_GPIO0 */
    {64, 0, PMX_SENSOR_MCLK, 125, 1}, /* S_GPIO0 */
    {64, 0, PMX_UART3_4_TX, 126, 1}, /* S_GPIO0 */
    {65, 0, PMX_SENSOR_MCLK2, 127, 3}, /* S_GPIO1 */
    {65, 0, PMX_SENSOR_CCIR16BITS, 130, 2}, /* S_GPIO1 */
    {65, 0, PMX_SENSOR_MCLK2, 132, 2}, /* S_GPIO1 */
    {65, 0, PMX_SENSOR_MCLK2, 134, 2}, /* S_GPIO1 */
    {65, 0, PMX_PWM0_3, 136, 1}, /* S_GPIO1 */
    {65, 0, PMX_SDIO2_CMD, 124, 1}, /* S_GPIO1 */
    {65, 0, PMX_SENSOR_12BITS, 137, 1}, /* S_GPIO1 */
    {65, 0, PMX_SENSOR_CCIR8BITS, 138, 1}, /* S_GPIO1 */
    {65, 0, PMX_SENSOR_MCLK2, 139, 1}, /* S_GPIO1 */
    {65, 0, PMX_UART3_4_RX, 126, 1}, /* S_GPIO1 */
    {66, 0, PMX_SENSOR_CCIR16BITS, 130, 2}, /* S_GPIO2 */
    {66, 0, PMX_PWM1_3, 140, 1}, /* S_GPIO2 */
    {66, 0, PMX_SDIO2_D0, 124, 1}, /* S_GPIO2 */
    {66, 0, PMX_SENSOR_12BITS, 137, 1}, /* S_GPIO2 */
    {66, 0, PMX_SENSOR_12BITS_2ND, 54, 1}, /* S_GPIO2 */
    {66, 0, PMX_SENSOR_CCIR8BITS, 138, 1}, /* S_GPIO2 */
    {66, 0, PMX_SENSOR_LVDS_VDHD, 141, 1}, /* S_GPIO2 */
    {67, 0, PMX_SENSOR_CCIR16BITS, 130, 2}, /* S_GPIO3 */
    {67, 0, PMX_PWM2_3, 142, 1}, /* S_GPIO3 */
    {67, 0, PMX_SB2_CS, 143, 1}, /* S_GPIO3 */
    {67, 0, PMX_SDIO2_D1, 124, 1}, /* S_GPIO3 */
    {67, 0, PMX_SENSOR_12BITS, 137, 1}, /* S_GPIO3 */
    {67, 0, PMX_SENSOR_12BITS_2ND, 54, 1}, /* S_GPIO3 */
    {67, 0, PMX_SENSOR_CCIR8BITS, 138, 1}, /* S_GPIO3 */
    {67, 0, PMX_SENSOR_LVDS_VDHD, 141, 1}, /* S_GPIO3 */
    {68, 0, PMX_I2C2_1_SCL, 144, 1}, /* S_GPIO4 */
    {68, 0, PMX_PWM3_3, 145, 1}, /* S_GPIO4 */
    {68, 0, PMX_SB2_CK, 143, 1}, /* S_GPIO4 */
    {68, 0, PMX_SENSOR2_12BITS, 52, 1}, /* S_GPIO4 */
    {68, 0, PMX_SENSOR2_LVDS_VDHD, 146, 1}, /* S_GPIO4 */
    {68, 0, PMX_UART3_5_TX, 147, 1}, /* S_GPIO4 */
    {69, 0, PMX_SPI_2_DI, 148, 2}, /* S_GPIO5 */
    {69, 0, PMX_I2C2_1_SDA, 144, 1}, /* S_GPIO5 */
    {69, 0, PMX_PWM4_3, 150, 1}, /* S_GPIO5 */
    {69, 0, PMX_SB2_DAT, 143, 1}, /* S_GPIO5 */
    {69, 0, PMX_SENSOR2_12BITS, 52, 1}, /* S_GPIO5 */
    {69, 0, PMX_SENSOR2_LVDS_VDHD, 146, 1}, /* S_GPIO5 */
    {69, 0, PMX_UART3_5_RX, 147, 1}, /* S_GPIO5 */
    {70, 0, PMX_PWM5_3, 151, 1}, /* S_GPIO6 */
    {70, 0, PMX_SB_CS, 152, 1}, /* S_GPIO6 */
    {70, 0, PMX_SPI_2_CS, 153, 1}, /* S_GPIO6 */
    {71, 0, PMX_SENSOR_CCIR16BITS, 130, 2}, /* S_GPIO7 */
    {71, 0, PMX_I2C_SCL_1, 154, 1}, /* S_GPIO7 */
    {71, 0, PMX_PWM6_3, 155, 1}, /* S_GPIO7 */
    {71, 0, PMX_SB_CK, 152, 1}, /* S_GPIO7 */
    {71, 0, PMX_SDIO2_D2, 124, 1}, /* S_GPIO7 */
    {71, 0, PMX_SENSOR_CCIR8BITS, 138, 1}, /* S_GPIO7 */
    {71, 0, PMX_SPI_2_CLK, 153, 1}, /* S_GPIO7 */
    {72, 0, PMX_I2C_SDA_1, 154, 1}, /* S_GPIO8 */
    {72, 0, PMX_PWM7_3, 156, 1}, /* S_GPIO8 */
    {72, 0, PMX_SB_DAT, 152, 1}, /* S_GPIO8 */
    {72, 0, PMX_SDIO2_D3, 124, 1}, /* S_GPIO8 */
    {72, 0, PMX_SENSOR2_MCLK_2ND, 157, 1}, /* S_GPIO8 */
    {72, 0, PMX_SPI_2_DO, 153, 1}, /* S_GPIO8 */
    {96, 0, PMX_PWM11_5, 158, 1}, /* L_GPIO0 */
    {97, 0, PMX_PICNT2_1, 159, 1}, /* L_GPIO1 */
    {98, 0, PMX_SP_CLK_2, 160, 1}, /* L_GPIO2 */
    {128, 0, PMX_ETH_LED1, 161, 1}, /* D_GPIO0 */
    {129, 0, PMX_ETH_LED1, 161, 1}, /* D_GPIO1 */
    {131, 0, PMX_PWM4_4, 162, 1}, /* D_GPIO3 */
    {131, 0, PMX_SB3_3_CS, 163, 1}, /* D_GPIO3 */
    {131, 0, PMX_SP_CLK_3, 164, 1}, /* D_GPIO3 */
    {132, 0, PMX_PWM5_4, 165, 1}, /* D_GPIO4 */
    {132, 0, PMX_SB3_3_CK, 163, 1}, /* D_GPIO4 */
    {132, 0, PMX_SP_CLK2_3, 166, 1}, /* D_GPIO4 */
    {133, 0, PMX_ETH_LED2, 167, 1}, /* D_GPIO5 */
    {133, 0, PMX_PWM6_4, 168, 1}, /* D_GPIO5 */
    {133, 0, PMX_SB3_3_DAT, 163, 1}, /* D_GPIO5 */
    {134, 0, PMX_ETH_LED2, 167, 1}, /* D_GPIO6 */
    {134, 0, PMX_PWM7_4, 169, 1}, /* D_GPIO6 */
    {135, 0, PMX_PWM11_4, 170, 1}, /* D_GPIO7 */
    {160, 0, PMX_SENSOR_CCIR_2, 171, 2}, /* H_GPIO0 */
    {160, NVT_UNGATED, PMX_SENSOR_12BITS, 137, 1}, /* H_GPIO0 */
    {160, 0, PMX_SENSOR_CCIR_2, 138, 1}, /* H_GPIO0 */
    {160, 0, PMX_MIPI_LVDS_DAT0, 1, 0}, /* H_GPIO0 */
    {161, 0, PMX_SENSOR_CCIR_2, 171, 2}, /* H_GPIO1 */
    {161, NVT_UNGATED, PMX_SENSOR_12BITS, 137, 1}, /* H_GPIO1 */
    {161, 0, PMX_SENSOR_CCIR_2, 138, 1}, /* H_GPIO1 */
    {161, 0, PMX_MIPI_LVDS_DAT0, 1, 0}, /* H_GPIO1 */
    {162, NVT_UNGATED, PMX_SENSOR_12BITS, 137, 1}, /* H_GPIO2 */
    {162, NVT_UNGATED, PMX_SENSOR_CCIR16BITS, 55, 1}, /* H_GPIO2 */
    {162, NVT_UNGATED, PMX_SENSOR_CCIR8BITS, 138, 1}, /* H_GPIO2 */
    {162, 0, PMX_MIPI_LVDS_DAT1, 1, 0}, /* H_GPIO2 */
    {163, NVT_UNGATED, PMX_SENSOR_12BITS, 137, 1}, /* H_GPIO3 */
    {163, NVT_UNGATED, PMX_SENSOR_CCIR16BITS, 55, 1}, /* H_GPIO3 */
    {163, NVT_UNGATED, PMX_SENSOR_CCIR8BITS, 138, 1}, /* H_GPIO3 */
    {163, 0, PMX_MIPI_LVDS_DAT1, 1, 0}, /* H_GPIO3 */
    {164, NVT_UNGATED, PMX_SENSOR_12BITS, 137, 1}, /* H_GPIO4 */
    {164, NVT_UNGATED, PMX_SENSOR_CCIR16BITS, 55, 1}, /* H_GPIO4 */
    {164, NVT_UNGATED, PMX_SENSOR_CCIR8BITS, 138, 1}, /* H_GPIO4 */
    {164, 0, PMX_MIPI_LVDS_CLK0, 1, 0}, /* H_GPIO4 */
    {165, NVT_UNGATED, PMX_SENSOR_12BITS, 137, 1}, /* H_GPIO5 */
    {165, NVT_UNGATED, PMX_SENSOR_CCIR16BITS, 55, 1}, /* H_GPIO5 */
    {165, NVT_UNGATED, PMX_SENSOR_CCIR8BITS, 138, 1}, /* H_GPIO5 */
    {165, 0, PMX_MIPI_LVDS_CLK0, 1, 0}, /* H_GPIO5 */
    {166, 0, PMX_PWM8_3, 173, 1}, /* H_GPIO6 */
    {166, NVT_UNGATED, PMX_SENSOR_12BITS, 137, 1}, /* H_GPIO6 */
    {166, NVT_UNGATED, PMX_SENSOR_CCIR16BITS, 55, 1}, /* H_GPIO6 */
    {166, NVT_UNGATED, PMX_SENSOR_CCIR8BITS, 138, 1}, /* H_GPIO6 */
    {166, 0, PMX_MIPI_LVDS_DAT2, 1, 0}, /* H_GPIO6 */
    {167, 0, PMX_PWM9_3, 174, 1}, /* H_GPIO7 */
    {167, NVT_UNGATED, PMX_SENSOR_12BITS, 137, 1}, /* H_GPIO7 */
    {167, NVT_UNGATED, PMX_SENSOR_CCIR16BITS, 55, 1}, /* H_GPIO7 */
    {167, NVT_UNGATED, PMX_SENSOR_CCIR8BITS, 138, 1}, /* H_GPIO7 */
    {167, 0, PMX_SENSOR_LVDS_VDHD2, 175, 1}, /* H_GPIO7 */
    {167, 0, PMX_MIPI_LVDS_DAT2, 1, 0}, /* H_GPIO7 */
    {168, 0, PMX_PWM10_3, 176, 1}, /* H_GPIO8 */
    {168, NVT_UNGATED, PMX_SENSOR_12BITS, 137, 1}, /* H_GPIO8 */
    {168, NVT_UNGATED, PMX_SENSOR_CCIR16BITS, 55, 1}, /* H_GPIO8 */
    {168, NVT_UNGATED, PMX_SENSOR_CCIR8BITS, 138, 1}, /* H_GPIO8 */
    {168, 0, PMX_SENSOR_LVDS_VDHD2, 175, 1}, /* H_GPIO8 */
    {168, 0, PMX_MIPI_LVDS_DAT3, 1, 0}, /* H_GPIO8 */
    {169, 0, PMX_I2C_2_SCL, 177, 1}, /* H_GPIO9 */
    {169, 0, PMX_PWM11_3, 178, 1}, /* H_GPIO9 */
    {169, NVT_UNGATED, PMX_SENSOR_12BITS, 137, 1}, /* H_GPIO9 */
    {169, NVT_UNGATED, PMX_SENSOR_CCIR16BITS, 55, 1}, /* H_GPIO9 */
    {169, NVT_UNGATED, PMX_SENSOR_CCIR8BITS, 138, 1}, /* H_GPIO9 */
    {169, 0, PMX_MIPI_LVDS_DAT3, 1, 0}, /* H_GPIO9 */
    {170, 0, PMX_SENSOR_CCIR_2, 171, 2}, /* H_GPIO10 */
    {170, 0, PMX_I2C_2_SDA, 177, 1}, /* H_GPIO10 */
    {170, NVT_UNGATED, PMX_SENSOR_12BITS, 137, 1}, /* H_GPIO10 */
    {170, 0, PMX_SENSOR_CCIR_2, 138, 1}, /* H_GPIO10 */
    {170, 0, PMX_MIPI_LVDS_CLK1, 1, 0}, /* H_GPIO10 */
    {171, 0, PMX_SENSOR_MCLK_2ND, 179, 3}, /* H_GPIO11 */
    {171, 0, PMX_SENSOR_CCIR_2, 171, 2}, /* H_GPIO11 */
    {171, 0, PMX_SENSOR_MCLK_2ND, 182, 2}, /* H_GPIO11 */
    {171, 0, PMX_SENSOR_MCLK_2ND, 184, 2}, /* H_GPIO11 */
    {171, NVT_UNGATED, PMX_SENSOR_12BITS, 137, 1}, /* H_GPIO11 */
    {171, 0, PMX_SENSOR_CCIR_2, 138, 1}, /* H_GPIO11 */
    {171, 0, PMX_SENSOR_MCLK_2ND, 186, 1}, /* H_GPIO11 */
    {171, 0, PMX_MIPI_LVDS_CLK1, 1, 0}, /* H_GPIO11 */
    {224, 0, PMX_ETH_MDIO, 187, 1}, /* DSI_GPIO0 */
    {224, 0, PMX_PWM0_5, 188, 1}, /* DSI_GPIO0 */
    {224, 0, PMX_UART3_1_TX, 189, 1}, /* DSI_GPIO0 */
    {225, 0, PMX_ETH_MDIO, 187, 1}, /* DSI_GPIO1 */
    {225, 0, PMX_PWM1_5, 190, 1}, /* DSI_GPIO1 */
    {225, 0, PMX_UART3_1_RX, 189, 1}, /* DSI_GPIO1 */
    {226, 0, PMX_UART3_1_RTS, 191, 2}, /* DSI_GPIO2 */
    {226, 0, PMX_UART3_1_RTS, 193, 2}, /* DSI_GPIO2 */
    {226, 0, PMX_ETH_RMII, 195, 1}, /* DSI_GPIO2 */
    {226, 0, PMX_PWM2_5, 196, 1}, /* DSI_GPIO2 */
    {226, 0, PMX_SDIO2_D0, 197, 1}, /* DSI_GPIO2 */
    {227, 0, PMX_UART3_1_CTS, 191, 2}, /* DSI_GPIO3 */
    {227, 0, PMX_ETH_RMII, 195, 1}, /* DSI_GPIO3 */
    {227, 0, PMX_PWM3_5, 198, 1}, /* DSI_GPIO3 */
    {227, 0, PMX_SDIO2_D1, 197, 1}, /* DSI_GPIO3 */
    {228, 0, PMX_ETH_RMII, 195, 1}, /* DSI_GPIO4 */
    {228, 0, PMX_PWM4_5, 199, 1}, /* DSI_GPIO4 */
    {228, 0, PMX_SDIO2_D2, 197, 1}, /* DSI_GPIO4 */
    {228, 0, PMX_SPI2_1_CS, 200, 1}, /* DSI_GPIO4 */
    {229, 0, PMX_ETH_RMII, 195, 1}, /* DSI_GPIO5 */
    {229, 0, PMX_PWM5_5, 201, 1}, /* DSI_GPIO5 */
    {229, 0, PMX_SDIO2_D3, 197, 1}, /* DSI_GPIO5 */
    {229, 0, PMX_SPI2_1_CLK, 200, 1}, /* DSI_GPIO5 */
    {230, 0, PMX_PWM6_5, 202, 1}, /* DSI_GPIO6 */
    {230, 0, PMX_SDIO2_CMD, 197, 1}, /* DSI_GPIO6 */
    {230, 0, PMX_SPI2_1_DO, 200, 1}, /* DSI_GPIO6 */
    {231, 0, PMX_SPI2_1_DI, 203, 2}, /* DSI_GPIO7 */
    {231, 0, PMX_ETH_RMII, 195, 1}, /* DSI_GPIO7 */
    {231, 0, PMX_PWM7_5, 205, 1}, /* DSI_GPIO7 */
    {231, 0, PMX_SDIO2_CLK, 197, 1}, /* DSI_GPIO7 */
    {232, 0, PMX_DMDAT0_2, 206, 3}, /* DSI_GPIO8 */
    {232, 0, PMX_ETH_RMII, 195, 1}, /* DSI_GPIO8 */
    {232, 0, PMX_I2C3_3_SDA, 209, 1}, /* DSI_GPIO8 */
    {232, 0, PMX_PWM8_5, 210, 1}, /* DSI_GPIO8 */
    {233, 0, PMX_DMDAT1_2, 206, 3}, /* DSI_GPIO9 */
    {233, 0, PMX_ETH_RMII, 211, 2}, /* DSI_GPIO9 */
    {233, 0, PMX_ETH_MDIO, 187, 1}, /* DSI_GPIO9 */
    {233, 0, PMX_ETH_RMII, 195, 1}, /* DSI_GPIO9 */
    {233, 0, PMX_I2C3_3_SCL, 209, 1}, /* DSI_GPIO9 */
    {233, 0, PMX_PWM9_5, 213, 1}, /* DSI_GPIO9 */
    {234, 0, PMX_DMCLK_2, 206, 3}, /* DSI_GPIO10 */
    {234, 0, PMX_ETH_EXTPHYCLK, 214, 1}, /* DSI_GPIO10 */
    {234, 0, PMX_ETH_MDIO, 187, 1}, /* DSI_GPIO10 */
    {234, 0, PMX_PWM10_5, 215, 1}, /* DSI_GPIO10 */
};

/* The field each function's walk row shows: {pad, name, reg,
 * shift, width, value}, reg NVT_GATE for the pad's gate bit. */
static const novatek_sel_t NA51089_sels[] = {
    {0, PMX_SDIO3_D0, 0x04, 17, 1, 1},
    {0, PMX_FSPI_DO, NVT_GATE, 0, 0, 0},
    {1, PMX_SDIO3_D1, 0x04, 17, 1, 1},
    {1, PMX_FSPI_DI, NVT_GATE, 0, 0, 0},
    {2, PMX_SDIO3_D2, 0x04, 17, 1, 1},
    {2, PMX_FSPI_WP, NVT_GATE, 0, 0, 0},
    {3, PMX_SDIO3_D3, 0x04, 17, 1, 1},
    {3, PMX_FSPI_HOLD, NVT_GATE, 0, 0, 0},
    {4, PMX_SDIO3_D4, 0x04, 17, 1, 1},
    {4, PMX_PWM0_4, 0x1C, 0, 3, 4},
    {5, PMX_SDIO3_D5, 0x04, 17, 1, 1},
    {5, PMX_PWM1_4, 0x1C, 3, 3, 4},
    {6, PMX_SDIO3_D6, 0x04, 17, 1, 1},
    {6, PMX_PWM2_4, 0x1C, 6, 3, 4},
    {7, PMX_SDIO3_D7, 0x04, 17, 1, 1},
    {7, PMX_PWM3_4, 0x1C, 9, 3, 4},
    {8, PMX_SDIO3_CLK, 0x04, 17, 1, 1},
    {8, PMX_FSPI_CLK, NVT_GATE, 0, 0, 0},
    {9, PMX_SDIO3_CMD, 0x04, 17, 1, 1},
    {9, PMX_SP_CLK2_2, 0x18, 10, 2, 2},
    {10, PMX_FSPI_CS, NVT_GATE, 0, 0, 0},
    {11, PMX_DMCLK_3, 0x18, 5, 1, 1},
    {11, PMX_I2C3_2_SCL, 0x14, 6, 2, 2},
    {11, PMX_I2S_MCLK_2, 0x18, 2, 2, 2},
    {11, PMX_PWM4_2, 0x1C, 12, 3, 2},
    {11, PMX_SDIO_CLK, 0x04, 14, 1, 1},
    {11, PMX_SPI3_2_CLK, 0x14, 12, 2, 2},
    {12, PMX_DMDAT0_3, 0x18, 5, 1, 1},
    {12, PMX_I2C3_2_SDA, 0x14, 6, 2, 2},
    {12, PMX_I2S_BCLK_2, 0x18, 0, 2, 2},
    {12, PMX_PWM5_2, 0x1C, 15, 3, 2},
    {12, PMX_SDIO_CMD, 0x04, 14, 1, 1},
    {12, PMX_SPI3_2_DO, 0x14, 12, 2, 2},
    {13, PMX_DMDAT1_3, 0x18, 5, 1, 1},
    {13, PMX_UART2_2_CTS, 0x24, 2, 2, 2},
    {13, PMX_I2S_SYNC_2, 0x18, 0, 2, 2},
    {13, PMX_PWM0_2, 0x1C, 0, 3, 2},
    {13, PMX_SDIO_D0, 0x04, 14, 1, 1},
    {13, PMX_SPI3_2_CS, 0x14, 12, 2, 2},
    {14, PMX_SPI3_2_DI, 0x14, 12, 2, 2},
    {14, PMX_UART2_2_RTS, 0x24, 2, 2, 2},
    {14, PMX_I2S_SDATAO_2, 0x18, 0, 2, 2},
    {14, PMX_PWM1_2, 0x1C, 3, 3, 2},
    {14, PMX_REMOTE_IN_2, 0x18, 7, 2, 2},
    {14, PMX_SDIO_D1, 0x04, 14, 1, 1},
    {15, PMX_REMOTE_EXT, 0x18, 7, 2, 2},
    {15, PMX_SPI_CH3_RDY, 0x14, 12, 2, 2},
    {15, PMX_I2S_SDATAI_2, 0x18, 0, 2, 2},
    {15, PMX_PWM2_2, 0x1C, 6, 3, 2},
    {15, PMX_SDIO_D2, 0x04, 14, 1, 1},
    {15, PMX_UART2_2_TX, 0x24, 2, 2, 2},
    {16, PMX_PWM3_2, 0x1C, 9, 3, 2},
    {16, PMX_SDIO_D3, 0x04, 14, 1, 1},
    {16, PMX_UART2_2_RX, 0x24, 2, 2, 2},
    {17, PMX_I2C2_2_SCL, 0x14, 4, 2, 2},
    {17, PMX_PWM6_2, 0x1C, 18, 3, 2},
    {17, PMX_SDIO2_CLK, 0x04, 18, 2, 1},
    {17, PMX_SPI_1_CLK, 0x14, 8, 2, 1},
    {18, PMX_I2C2_2_SDA, 0x14, 4, 2, 2},
    {18, PMX_PWM7_2, 0x1C, 21, 3, 2},
    {18, PMX_SDIO2_CMD, 0x04, 18, 2, 1},
    {18, PMX_SPI_1_DO, 0x14, 8, 2, 1},
    {19, PMX_UART3_2_CTS, 0x24, 4, 3, 2},
    {19, PMX_PWM8_2, 0x18, 16, 3, 2},
    {19, PMX_SDIO2_D0, 0x04, 18, 2, 1},
    {19, PMX_SPI_1_CS, 0x14, 8, 2, 1},
    {20, PMX_SPI_1_DI, 0x14, 8, 2, 1},
    {20, PMX_UART3_2_RTS, 0x24, 4, 3, 2},
    {20, PMX_PWM9_2, 0x18, 19, 3, 2},
    {20, PMX_SDIO2_D1, 0x04, 18, 2, 1},
    {21, PMX_PWM10_2, 0x18, 22, 3, 2},
    {21, PMX_SDIO2_D2, 0x04, 18, 2, 1},
    {21, PMX_UART3_2_TX, 0x24, 4, 3, 2},
    {22, PMX_PWM11_2, 0x18, 25, 3, 2},
    {22, PMX_SDIO2_D3, 0x04, 18, 2, 1},
    {22, PMX_UART3_2_RX, 0x24, 4, 3, 2},
    {32, PMX_ETH_RMII_2, 0x14, 30, 2, 2},
    {32, PMX_PWM0_1, 0x1C, 0, 3, 1},
    {32, PMX_SENSOR2_12BITS, 0x0C, 4, 2, 1},
    {32, PMX_SENSOR2_CCIR8BITS, 0x0C, 4, 2, 2},
    {32, PMX_SENSOR_12BITS_2ND, 0x0C, 0, 3, 2},
    {32, PMX_SENSOR_CCIR16BITS, 0x0C, 0, 3, 4},
    {32, PMX_SPI2_2_CS, 0x14, 10, 2, 2},
    {32, PMX_UART2_3_TX, 0x24, 2, 2, 3},
    {33, PMX_ETH_RMII_2, 0x14, 30, 2, 2},
    {33, PMX_PWM1_1, 0x1C, 3, 3, 1},
    {33, PMX_SENSOR2_12BITS, 0x0C, 4, 2, 1},
    {33, PMX_SENSOR2_CCIR8BITS, 0x0C, 4, 2, 2},
    {33, PMX_SENSOR_12BITS_2ND, 0x0C, 0, 3, 2},
    {33, PMX_SENSOR_CCIR16BITS, 0x0C, 0, 3, 4},
    {33, PMX_SPI2_2_CLK, 0x14, 10, 2, 2},
    {33, PMX_UART2_3_RX, 0x24, 2, 2, 3},
    {34, PMX_UART2_3_RTS, 0x24, 2, 2, 3},
    {34, PMX_ETH_RMII_2, 0x14, 30, 2, 2},
    {34, PMX_PWM2_1, 0x1C, 6, 3, 1},
    {34, PMX_SENSOR2_12BITS, 0x0C, 4, 2, 1},
    {34, PMX_SENSOR2_CCIR8BITS, 0x0C, 4, 2, 2},
    {34, PMX_SENSOR_12BITS_2ND, 0x0C, 0, 3, 2},
    {34, PMX_SENSOR_CCIR16BITS, 0x0C, 0, 3, 4},
    {34, PMX_SPI2_2_DO, 0x14, 10, 2, 2},
    {35, PMX_SPI2_2_DI, 0x14, 10, 2, 2},
    {35, PMX_UART2_3_CTS, 0x24, 2, 2, 3},
    {35, PMX_ETH_RMII_2, 0x14, 30, 2, 2},
    {35, PMX_PWM3_1, 0x1C, 9, 3, 1},
    {35, PMX_SENSOR2_12BITS, 0x0C, 4, 2, 1},
    {35, PMX_SENSOR2_CCIR8BITS, 0x0C, 4, 2, 2},
    {35, PMX_SENSOR_12BITS_2ND, 0x0C, 0, 3, 2},
    {35, PMX_SENSOR_CCIR16BITS, 0x0C, 0, 3, 4},
    {36, PMX_ETH_RMII_2, 0x14, 30, 2, 2},
    {36, PMX_PWM4_1, 0x1C, 12, 3, 1},
    {36, PMX_SENSOR2_12BITS, 0x0C, 4, 2, 1},
    {36, PMX_SENSOR2_CCIR8BITS, 0x0C, 4, 2, 2},
    {36, PMX_SENSOR_12BITS_2ND, 0x0C, 0, 3, 2},
    {36, PMX_SENSOR_CCIR16BITS, 0x0C, 0, 3, 4},
    {36, PMX_SPI3_3_CS, 0x14, 12, 2, 3},
    {36, PMX_UART3_3_TX, 0x24, 4, 3, 3},
    {37, PMX_ETH_RMII_2, 0x14, 30, 2, 2},
    {37, PMX_PWM5_1, 0x1C, 15, 3, 1},
    {37, PMX_SENSOR2_12BITS, 0x0C, 4, 2, 1},
    {37, PMX_SENSOR2_CCIR8BITS, 0x0C, 4, 2, 2},
    {37, PMX_SENSOR_12BITS_2ND, 0x0C, 0, 3, 2},
    {37, PMX_SENSOR_CCIR16BITS, 0x0C, 0, 3, 4},
    {37, PMX_SPI3_3_CLK, 0x14, 12, 2, 3},
    {37, PMX_UART3_3_RX, 0x24, 4, 3, 3},
    {38, PMX_UART3_3_RTS, 0x24, 4, 3, 3},
    {38, PMX_PWM6_1, 0x1C, 18, 3, 1},
    {38, PMX_SENSOR2_12BITS, 0x0C, 4, 2, 1},
    {38, PMX_SENSOR2_CCIR8BITS, 0x0C, 4, 2, 2},
    {38, PMX_SENSOR_12BITS_2ND, 0x0C, 0, 3, 2},
    {38, PMX_SENSOR_CCIR16BITS, 0x0C, 0, 3, 4},
    {38, PMX_SPI3_3_DO, 0x14, 12, 2, 3},
    {39, PMX_ETH_EXTPHYCLK, 0x14, 30, 2, 2},
    {39, PMX_SPI3_3_DI, 0x14, 12, 2, 3},
    {39, PMX_UART3_3_CTS, 0x24, 4, 3, 3},
    {39, PMX_PWM7_1, 0x1C, 21, 3, 1},
    {39, PMX_SB4_CS, 0x14, 26, 1, 1},
    {39, PMX_SENSOR2_12BITS, 0x0C, 4, 2, 1},
    {39, PMX_SENSOR2_CCIR8BITS, 0x0C, 4, 2, 2},
    {39, PMX_SENSOR_12BITS_2ND, 0x0C, 0, 3, 2},
    {39, PMX_SENSOR_CCIR16BITS, 0x0C, 0, 3, 4},
    {40, PMX_SPI_CH3_RDY, 0x14, 12, 2, 3},
    {40, PMX_ETH_RMII_2, 0x14, 30, 2, 2},
    {40, PMX_I2S_MCLK_1, 0x18, 2, 2, 1},
    {40, PMX_PWM8_1, 0x18, 16, 3, 1},
    {40, PMX_SB4_CK, 0x14, 26, 1, 1},
    {40, PMX_SENSOR2_12BITS, 0x0C, 4, 2, 1},
    {40, PMX_SENSOR2_CCIR8BITS, 0x0C, 4, 2, 2},
    {40, PMX_SENSOR_12BITS_2ND, 0x0C, 0, 3, 2},
    {41, PMX_ETH_MDIO_2, 0x14, 2, 2, 2},
    {41, PMX_I2S_BCLK_1, 0x18, 0, 2, 1},
    {41, PMX_PWM9_1, 0x18, 19, 3, 1},
    {41, PMX_SB4_DAT, 0x14, 26, 1, 1},
    {41, PMX_SENSOR2_12BITS, 0x0C, 4, 2, 1},
    {41, PMX_SENSOR2_CCIR8BITS, 0x0C, 4, 2, 2},
    {41, PMX_SENSOR_12BITS_2ND, 0x0C, 0, 3, 2},
    {42, PMX_ETH_MDIO_2, 0x14, 2, 2, 2},
    {42, PMX_I2S_SYNC_1, 0x18, 0, 2, 1},
    {42, PMX_PWM10_1, 0x18, 22, 3, 1},
    {42, PMX_SB3_1_CS, 0x14, 24, 2, 1},
    {42, PMX_SENSOR2_12BITS, 0x0C, 4, 2, 1},
    {42, PMX_SENSOR2_CCIR8BITS, 0x0C, 4, 2, 2},
    {42, PMX_SENSOR_12BITS_2ND, 0x0C, 0, 3, 2},
    {43, PMX_I2S_SDATAO_1, 0x18, 0, 2, 1},
    {43, PMX_PWM11_1, 0x18, 25, 3, 1},
    {43, PMX_SB3_1_CK, 0x14, 24, 2, 1},
    {43, PMX_SENSOR2_12BITS, 0x0C, 4, 2, 1},
    {43, PMX_SENSOR2_CCIR8BITS, 0x0C, 4, 2, 2},
    {43, PMX_SENSOR_12BITS_2ND, 0x0C, 0, 3, 2},
    {44, PMX_SENSOR2_SN3_MCLK, 0x0C, 16, 1, 1},
    {44, PMX_SPI_CH3_RDY, 0x14, 12, 2, 1},
    {44, PMX_I2S_SDATAI_1, 0x18, 0, 2, 1},
    {44, PMX_PICNT_1, 0x1C, 26, 2, 1},
    {44, PMX_SB3_1_DAT, 0x14, 24, 2, 1},
    {44, PMX_SENSOR2_12BITS, 0x0C, 4, 2, 1},
    {44, PMX_SENSOR_12BITS_2ND, 0x0C, 0, 3, 2},
    {49, PMX_DMDAT0_1, 0x18, 5, 1, 1},
    {49, PMX_PICNT3_1, 0x1C, 30, 2, 1},
    {49, PMX_REMOTE_IN_1, 0x18, 7, 2, 1},
    {49, PMX_SB3_2_CS, 0x14, 24, 2, 2},
    {49, PMX_SPI3_1_CS, 0x14, 12, 2, 1},
    {49, PMX_UART2_1_TX, 0x24, 2, 2, 1},
    {50, PMX_DMDAT1_1, 0x18, 5, 1, 1},
    {50, PMX_REMOTE_EXT, 0x18, 7, 2, 1},
    {50, PMX_PICNT_2, 0x1C, 26, 2, 2},
    {50, PMX_SB3_2_CK, 0x14, 24, 2, 2},
    {50, PMX_SPI3_1_CLK, 0x14, 12, 2, 1},
    {50, PMX_UART2_1_RX, 0x24, 2, 2, 1},
    {51, PMX_DMCLK_1, 0x18, 5, 1, 1},
    {51, PMX_UART2_1_RTS, 0x24, 2, 2, 1},
    {51, PMX_PICNT2_2, 0x1C, 28, 2, 2},
    {51, PMX_RTC_CLK, 0x18, 9, 1, 1},
    {51, PMX_SB3_2_DAT, 0x14, 24, 2, 2},
    {51, PMX_SPI3_1_DO, 0x14, 12, 2, 1},
    {52, PMX_SPI3_1_DI, 0x14, 12, 2, 1},
    {52, PMX_UART2_1_CTS, 0x24, 2, 2, 1},
    {52, PMX_PICNT3_2, 0x1C, 30, 2, 2},
    {52, PMX_SP_CLK_1, 0x0C, 18, 2, 1},
    {53, PMX_I2C3_1_SDA, 0x14, 6, 2, 1},
    {53, PMX_SP_CLK2_1, 0x18, 10, 2, 1},
    {54, PMX_I2C3_1_SCL, 0x14, 6, 2, 1},
    {55, PMX_UART_TX, 0x24, 0, 1, 1},
    {56, PMX_UART_RX, 0x24, 0, 1, 1},
    {64, PMX_SDIO2_CLK, 0x04, 18, 2, 2},
    {64, PMX_SENSOR_MCLK, 0x0C, 8, 2, 1},
    {64, PMX_UART3_4_TX, 0x24, 4, 3, 4},
    {65, PMX_SENSOR_MCLK2, 0x0C, 12, 2, 1},
    {65, PMX_SENSOR_CCIR16BITS, 0x0C, 0, 3, 4},
    {65, PMX_PWM0_3, 0x1C, 0, 3, 3},
    {65, PMX_SDIO2_CMD, 0x04, 18, 2, 2},
    {65, PMX_SENSOR_12BITS, 0x0C, 0, 3, 1},
    {65, PMX_SENSOR_CCIR8BITS, 0x0C, 0, 3, 3},
    {65, PMX_UART3_4_RX, 0x24, 4, 3, 4},
    {66, PMX_SENSOR_CCIR16BITS, 0x0C, 0, 3, 4},
    {66, PMX_PWM1_3, 0x1C, 3, 3, 3},
    {66, PMX_SDIO2_D0, 0x04, 18, 2, 2},
    {66, PMX_SENSOR_12BITS, 0x0C, 0, 3, 1},
    {66, PMX_SENSOR_12BITS_2ND, 0x0C, 0, 3, 2},
    {66, PMX_SENSOR_CCIR8BITS, 0x0C, 0, 3, 3},
    {66, PMX_SENSOR_LVDS_VDHD, 0x0C, 10, 2, 1},
    {67, PMX_SENSOR_CCIR16BITS, 0x0C, 0, 3, 4},
    {67, PMX_PWM2_3, 0x1C, 6, 3, 3},
    {67, PMX_SB2_CS, 0x14, 22, 1, 1},
    {67, PMX_SDIO2_D1, 0x04, 18, 2, 2},
    {67, PMX_SENSOR_12BITS, 0x0C, 0, 3, 1},
    {67, PMX_SENSOR_12BITS_2ND, 0x0C, 0, 3, 2},
    {67, PMX_SENSOR_CCIR8BITS, 0x0C, 0, 3, 3},
    {67, PMX_SENSOR_LVDS_VDHD, 0x0C, 10, 2, 1},
    {68, PMX_I2C2_1_SCL, 0x14, 4, 2, 1},
    {68, PMX_PWM3_3, 0x1C, 9, 3, 3},
    {68, PMX_SB2_CK, 0x14, 22, 1, 1},
    {68, PMX_SENSOR2_12BITS, 0x0C, 4, 2, 1},
    {68, PMX_SENSOR2_LVDS_VDHD, 0x0C, 14, 2, 1},
    {68, PMX_UART3_5_TX, 0x24, 4, 3, 5},
    {69, PMX_SPI_2_DI, 0x14, 8, 2, 2},
    {69, PMX_I2C2_1_SDA, 0x14, 4, 2, 1},
    {69, PMX_PWM4_3, 0x1C, 12, 3, 3},
    {69, PMX_SB2_DAT, 0x14, 22, 1, 1},
    {69, PMX_SENSOR2_12BITS, 0x0C, 4, 2, 1},
    {69, PMX_SENSOR2_LVDS_VDHD, 0x0C, 14, 2, 1},
    {69, PMX_UART3_5_RX, 0x24, 4, 3, 5},
    {70, PMX_PWM5_3, 0x1C, 15, 3, 3},
    {70, PMX_SB_CS, 0x14, 20, 1, 1},
    {70, PMX_SPI_2_CS, 0x14, 8, 2, 2},
    {71, PMX_SENSOR_CCIR16BITS, 0x0C, 0, 3, 4},
    {71, PMX_I2C_SCL_1, 0x14, 0, 2, 1},
    {71, PMX_PWM6_3, 0x1C, 18, 3, 3},
    {71, PMX_SB_CK, 0x14, 20, 1, 1},
    {71, PMX_SDIO2_D2, 0x04, 18, 2, 2},
    {71, PMX_SENSOR_CCIR8BITS, 0x0C, 0, 3, 3},
    {71, PMX_SPI_2_CLK, 0x14, 8, 2, 2},
    {72, PMX_I2C_SDA_1, 0x14, 0, 2, 1},
    {72, PMX_PWM7_3, 0x1C, 21, 3, 3},
    {72, PMX_SB_DAT, 0x14, 20, 1, 1},
    {72, PMX_SDIO2_D3, 0x04, 18, 2, 2},
    {72, PMX_SENSOR2_MCLK_2ND, 0x0C, 12, 2, 2},
    {72, PMX_SPI_2_DO, 0x14, 8, 2, 2},
    {96, PMX_PWM11_5, 0x18, 25, 3, 5},
    {97, PMX_PICNT2_1, 0x1C, 28, 2, 1},
    {98, PMX_SP_CLK_2, 0x0C, 18, 2, 2},
    {128, PMX_ETH_LED1, 0x18, 13, 2, 1},
    {129, PMX_ETH_LED1, 0x18, 13, 2, 1},
    {131, PMX_PWM4_4, 0x1C, 12, 3, 4},
    {131, PMX_SB3_3_CS, 0x14, 24, 2, 3},
    {131, PMX_SP_CLK_3, 0x0C, 18, 2, 3},
    {132, PMX_PWM5_4, 0x1C, 15, 3, 4},
    {132, PMX_SB3_3_CK, 0x14, 24, 2, 3},
    {132, PMX_SP_CLK2_3, 0x18, 10, 2, 3},
    {133, PMX_ETH_LED2, 0x18, 13, 2, 2},
    {133, PMX_PWM6_4, 0x1C, 18, 3, 4},
    {133, PMX_SB3_3_DAT, 0x14, 24, 2, 3},
    {134, PMX_ETH_LED2, 0x18, 13, 2, 2},
    {134, PMX_PWM7_4, 0x1C, 21, 3, 4},
    {135, PMX_PWM11_4, 0x18, 25, 3, 4},
    {160, PMX_SENSOR_CCIR_2, 0x0C, 0, 3, 3},
    {160, PMX_SENSOR_12BITS, 0x0C, 0, 3, 1},
    {160, PMX_MIPI_LVDS_DAT0, NVT_GATE, 0, 0, 0},
    {161, PMX_SENSOR_CCIR_2, 0x0C, 0, 3, 3},
    {161, PMX_SENSOR_12BITS, 0x0C, 0, 3, 1},
    {161, PMX_MIPI_LVDS_DAT0, NVT_GATE, 0, 0, 0},
    {162, PMX_SENSOR_12BITS, 0x0C, 0, 3, 1},
    {162, PMX_SENSOR_CCIR16BITS, 0x0C, 0, 3, 4},
    {162, PMX_SENSOR_CCIR8BITS, 0x0C, 0, 3, 3},
    {162, PMX_MIPI_LVDS_DAT1, NVT_GATE, 0, 0, 0},
    {163, PMX_SENSOR_12BITS, 0x0C, 0, 3, 1},
    {163, PMX_SENSOR_CCIR16BITS, 0x0C, 0, 3, 4},
    {163, PMX_SENSOR_CCIR8BITS, 0x0C, 0, 3, 3},
    {163, PMX_MIPI_LVDS_DAT1, NVT_GATE, 0, 0, 0},
    {164, PMX_SENSOR_12BITS, 0x0C, 0, 3, 1},
    {164, PMX_SENSOR_CCIR16BITS, 0x0C, 0, 3, 4},
    {164, PMX_SENSOR_CCIR8BITS, 0x0C, 0, 3, 3},
    {164, PMX_MIPI_LVDS_CLK0, NVT_GATE, 0, 0, 0},
    {165, PMX_SENSOR_12BITS, 0x0C, 0, 3, 1},
    {165, PMX_SENSOR_CCIR16BITS, 0x0C, 0, 3, 4},
    {165, PMX_SENSOR_CCIR8BITS, 0x0C, 0, 3, 3},
    {165, PMX_MIPI_LVDS_CLK0, NVT_GATE, 0, 0, 0},
    {166, PMX_PWM8_3, 0x18, 16, 3, 3},
    {166, PMX_SENSOR_12BITS, 0x0C, 0, 3, 1},
    {166, PMX_SENSOR_CCIR16BITS, 0x0C, 0, 3, 4},
    {166, PMX_SENSOR_CCIR8BITS, 0x0C, 0, 3, 3},
    {166, PMX_MIPI_LVDS_DAT2, NVT_GATE, 0, 0, 0},
    {167, PMX_PWM9_3, 0x18, 19, 3, 3},
    {167, PMX_SENSOR_12BITS, 0x0C, 0, 3, 1},
    {167, PMX_SENSOR_CCIR16BITS, 0x0C, 0, 3, 4},
    {167, PMX_SENSOR_CCIR8BITS, 0x0C, 0, 3, 3},
    {167, PMX_SENSOR_LVDS_VDHD2, 0x0C, 10, 2, 2},
    {167, PMX_MIPI_LVDS_DAT2, NVT_GATE, 0, 0, 0},
    {168, PMX_PWM10_3, 0x18, 22, 3, 3},
    {168, PMX_SENSOR_12BITS, 0x0C, 0, 3, 1},
    {168, PMX_SENSOR_CCIR16BITS, 0x0C, 0, 3, 4},
    {168, PMX_SENSOR_CCIR8BITS, 0x0C, 0, 3, 3},
    {168, PMX_SENSOR_LVDS_VDHD2, 0x0C, 10, 2, 2},
    {168, PMX_MIPI_LVDS_DAT3, NVT_GATE, 0, 0, 0},
    {169, PMX_I2C_2_SCL, 0x14, 0, 2, 2},
    {169, PMX_PWM11_3, 0x18, 25, 3, 3},
    {169, PMX_SENSOR_12BITS, 0x0C, 0, 3, 1},
    {169, PMX_SENSOR_CCIR16BITS, 0x0C, 0, 3, 4},
    {169, PMX_SENSOR_CCIR8BITS, 0x0C, 0, 3, 3},
    {169, PMX_MIPI_LVDS_DAT3, NVT_GATE, 0, 0, 0},
    {170, PMX_SENSOR_CCIR_2, 0x0C, 0, 3, 3},
    {170, PMX_I2C_2_SDA, 0x14, 0, 2, 2},
    {170, PMX_SENSOR_12BITS, 0x0C, 0, 3, 1},
    {170, PMX_MIPI_LVDS_CLK1, NVT_GATE, 0, 0, 0},
    {171, PMX_SENSOR_MCLK_2ND, 0x0C, 8, 2, 2},
    {171, PMX_SENSOR_CCIR_2, 0x0C, 0, 3, 3},
    {171, PMX_SENSOR_12BITS, 0x0C, 0, 3, 1},
    {171, PMX_MIPI_LVDS_CLK1, NVT_GATE, 0, 0, 0},
    {224, PMX_ETH_MDIO, 0x14, 2, 2, 1},
    {224, PMX_PWM0_5, 0x1C, 0, 3, 5},
    {224, PMX_UART3_1_TX, 0x24, 4, 3, 1},
    {225, PMX_ETH_MDIO, 0x14, 2, 2, 1},
    {225, PMX_PWM1_5, 0x1C, 3, 3, 5},
    {225, PMX_UART3_1_RX, 0x24, 4, 3, 1},
    {226, PMX_UART3_1_RTS, 0x24, 4, 3, 1},
    {226, PMX_ETH_RMII, 0x14, 30, 2, 1},
    {226, PMX_PWM2_5, 0x1C, 6, 3, 5},
    {226, PMX_SDIO2_D0, 0x04, 18, 2, 3},
    {227, PMX_UART3_1_CTS, 0x24, 4, 3, 1},
    {227, PMX_ETH_RMII, 0x14, 30, 2, 1},
    {227, PMX_PWM3_5, 0x1C, 9, 3, 5},
    {227, PMX_SDIO2_D1, 0x04, 18, 2, 3},
    {228, PMX_ETH_RMII, 0x14, 30, 2, 1},
    {228, PMX_PWM4_5, 0x1C, 12, 3, 5},
    {228, PMX_SDIO2_D2, 0x04, 18, 2, 3},
    {228, PMX_SPI2_1_CS, 0x14, 10, 2, 1},
    {229, PMX_ETH_RMII, 0x14, 30, 2, 1},
    {229, PMX_PWM5_5, 0x1C, 15, 3, 5},
    {229, PMX_SDIO2_D3, 0x04, 18, 2, 3},
    {229, PMX_SPI2_1_CLK, 0x14, 10, 2, 1},
    {230, PMX_PWM6_5, 0x1C, 18, 3, 5},
    {230, PMX_SDIO2_CMD, 0x04, 18, 2, 3},
    {230, PMX_SPI2_1_DO, 0x14, 10, 2, 1},
    {231, PMX_SPI2_1_DI, 0x14, 10, 2, 1},
    {231, PMX_ETH_RMII, 0x14, 30, 2, 1},
    {231, PMX_PWM7_5, 0x1C, 21, 3, 5},
    {231, PMX_SDIO2_CLK, 0x04, 18, 2, 3},
    {232, PMX_DMDAT0_2, 0x18, 5, 1, 1},
    {232, PMX_ETH_RMII, 0x14, 30, 2, 1},
    {232, PMX_I2C3_3_SDA, 0x14, 6, 2, 3},
    {232, PMX_PWM8_5, 0x18, 16, 3, 5},
    {233, PMX_DMDAT1_2, 0x18, 5, 1, 1},
    {233, PMX_ETH_RMII, 0x14, 30, 2, 1},
    {233, PMX_ETH_MDIO, 0x14, 2, 2, 1},
    {233, PMX_I2C3_3_SCL, 0x14, 6, 2, 3},
    {233, PMX_PWM9_5, 0x18, 19, 3, 5},
    {234, PMX_DMCLK_2, 0x18, 5, 1, 1},
    {234, PMX_ETH_EXTPHYCLK, 0x18, 28, 1, 1},
    {234, PMX_ETH_MDIO, 0x14, 2, 2, 1},
    {234, PMX_PWM10_5, 0x18, 22, 3, 5},
};

static const novatek_soc_t NA51089_padmux = {
    NA51089_pads, 102, NA51089_claims, 388, NA51089_conds,
    NA51089_sels, 368,
};

#endif /* HAL_NOVATEK_PADMUX_H */
