#!/usr/bin/env python3
"""Build the interned pad-function name table from the MUXCTRL tables.

WHY THIS EXISTS

A muxctrl row used to hold its function names as `const char *`. In a
position-independent executable every one of those pointers costs a
R_ARM_RELATIVE entry -- eight bytes of `.rel.dyn` on top of the four-byte
slot -- so pointing at a pad name cost four times more than storing it.
Measured on a hi3516ev200 consumer: the V4 tables were 8,096 bytes of
`.data.rel.ro`, the 1,424 relocations into them were 11,392 bytes, and all
269 distinct names they pointed at were 2,862 bytes.

So the rows hold `uint16_t` offsets into one blob instead, and the blob is
this file's output. No pointers, no relocations, and the names still dedupe:
V4 goes from 25,962 bytes to 11,466.

HOW

The blob is a struct of `char` arrays, one per distinct name, and an offset
is `offsetof()` of its member -- an integer constant expression, so it can
initialise a `uint16_t` in a static initialiser. Each member is its own
NUL-terminated string, so padding between members (which no compiler inserts
between char arrays, but which C permits) would waste a byte and break
nothing.

A member is compiled only when some table that uses the name is, so a
consumer carrying one family pays for that family's names alone. `_none` is
first and one byte, which is what reserves offset 0 as the end-of-list
marker.

USAGE

    tools/gen_padmux_names.py            # regenerate src/padmux_names.{h,c}
    tools/gen_padmux_names.py --check    # exit 1 if they are stale (CI)
    tools/gen_padmux_names.py --rewrite  # "NAME" -> PMX_NAME in the tables

`--rewrite` is the one-time conversion and is kept because it is also how you
undo a bad merge in the tables. It is idempotent.
"""

import argparse
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Each table file, and the condition under which its rows are compiled.
#
# reginfo.c is split into per-family `#if defined(IPCHW_PADMUX_Vx)` blocks and
# is parsed for them. The other two are pad-free register dumps for the
# `reginfo` subcommand: they carry no family blocks, and the whole file is
# behind one condition -- including `!STANDALONE_LIBRARY`, because libipchw
# does not include them at all and must not pay for their names.
# The third field is how names are spelled in the file.
#
#   "muxctrl" -- MUXCTRL(name, addr, ...) rows, one per line or wrapped.
#   "table"   -- a generated C initialiser where EVERY string literal is a
#                pad or function name. Comments are stripped first, because
#                the banner in both of those files quotes example names and
#                interning a name nothing indexes would be a silent leak
#                into the blob.
SOURCES = [
    ("src/reginfo.c", None, "muxctrl"),
    (
        "src/hal/ingenic_reginfo.h",
        "defined(IPCHW_VENDOR_INGENIC) && !defined(STANDALONE_LIBRARY)",
        "muxctrl",
    ),
    (
        "src/hal/sstar_reginfo.h",
        "defined(IPCHW_VENDOR_SSTAR) && !defined(STANDALONE_LIBRARY)",
        "muxctrl",
    ),
    ("src/hal/ingenic_padmux.h", "defined(IPCHW_PADMUX_INGENIC)", "table"),
    ("src/hal/sstar_padmux.h", "defined(IPCHW_PADMUX_SSTAR)", "table"),
]

FAMILY_OPEN = re.compile(r"^#if defined\((IPCHW_PADMUX_[A-Z0-9_]+)\)")
FAMILY_CLOSE = re.compile(r"^#endif\s*/\*\s*(IPCHW_PADMUX_[A-Z0-9_]+)")
MUXCTRL_OPEN = re.compile(r"^\s*MUXCTRL\(")
STRING = re.compile(r'"((?:[^"\\]|\\.)*)"')
PMXREF = re.compile(r"\bPMX_([A-Za-z0-9_]+)\b")

HEADER = "src/padmux_names.h"
SOURCE = "src/padmux_names.c"

BANNER = """/* Generated by tools/gen_padmux_names.py -- do not edit.
 *
 * The pad function names every MUXCTRL table refers to, interned so a row can
 * hold a uint16_t offset instead of a pointer. See the generator for why: in a
 * PIE a pointer into this blob costs three times what the string it points at
 * does, and there are four times more pointers than distinct names.
 */
"""


def mangle(name):
    """A C identifier for a pad function name.

    Sixteen names in the HiSilicon tables spell a pad that two peripherals
    reach under one selector value -- "SDIO0_CCLK_OUT/EMMC_CLK_OUT". The slash
    is the only character in any of them that an identifier cannot hold, and
    it becomes a double underscore. The member's initialiser carries the true
    spelling, so the mangling never reaches a caller.
    """
    ident = re.sub(r"[^A-Za-z0-9_]", "__", name)
    if not ident or ident[0].isdigit():
        ident = "_" + ident
    return ident


def demangle(ident):
    """The pad function name a PMX_ identifier stands for.

    The inverse of mangle(), which is only a function because no name in any
    table contains a double underscore of its own -- selftest() asserts that,
    so a name that broke it would fail the check rather than silently read
    back as a different pad function.
    """
    if ident[0] == "_" and len(ident) > 1 and ident[1].isdigit():
        ident = ident[1:]
    return ident.replace("__", "/")



def map_code(line, in_block, fn):
    """Apply `fn` to each run of CODE in `line`, leaving comments untouched.

    Returns (rebuilt line, block-comment state after it). With `fn` as
    identity the line comes back byte for byte, which is what makes it safe
    to run over a whole file.

    Only good enough for these five files -- it does not know about a `/*`
    inside a string literal, and none of them has one. It exists because a
    name quoted in a banner comment ("PB25", the spelling the datasheet uses)
    must not reach the blob, and because the generated SigmaStar table ends
    half its rows with a `/* 42 */` pad-id comment that a naive split would
    either eat or stop the substitution reaching.
    """
    out = []
    code = []
    i = 0

    def flush():
        if code:
            out.append(fn("".join(code)))
            del code[:]

    while i < len(line):
        if in_block:
            end = line.find("*/", i)
            if end < 0:
                out.append(line[i:])
                return "".join(out), True
            out.append(line[i:end + 2])
            i = end + 2
            in_block = False
            continue
        if line.startswith("/*", i):
            flush()
            in_block = True
            out.append("/*")
            i += 2
            continue
        if line.startswith("//", i):
            flush()
            out.append(line[i:])
            return "".join(out), False
        code.append(line[i])
        i += 1
    flush()
    return "".join(out), in_block


def code_of(line, in_block):
    """Just the code part, for the scan."""
    seen = []
    _, after = map_code(line, in_block, lambda c: seen.append(c) or c)
    return "".join(seen), after


def scan():
    """name -> (spelling, {guard expression, ...}), in first-seen order."""
    names = {}
    for rel, fixed_guard, mode in SOURCES:
        path = os.path.join(ROOT, rel)
        family = None
        pending = None
        in_block = False

        if mode == "table":
            for line in open(path, encoding="utf-8"):
                code, in_block = code_of(line, in_block)
                # An #include's path is a string literal and is not a pad
                # name. Nothing else in these two files is a directive.
                if code.lstrip().startswith("#"):
                    continue
                for raw in STRING.findall(code):
                    spelling = raw.encode().decode("unicode_escape")
                    names.setdefault(spelling, set()).add(fixed_guard)
                for ident in PMXREF.findall(code):
                    names.setdefault(demangle(ident), set()).add(fixed_guard)
            continue

        for line in open(path, encoding="utf-8"):
            if fixed_guard is None:
                m = FAMILY_OPEN.match(line)
                if m:
                    family = m.group(1)
                    continue
                if FAMILY_CLOSE.match(line):
                    family = None
                    continue

            if MUXCTRL_OPEN.match(line):
                pending = line
            elif pending is not None:
                pending += line
            else:
                continue

            # A MUXCTRL spans lines when clang-format wraps its arguments.
            if pending.count("(") > pending.count(")"):
                continue

            guard = fixed_guard or (
                "defined(%s)" % family if family else None
            )
            if guard is None:
                raise SystemExit(
                    "%s: MUXCTRL outside any family guard:\n%s" % (rel, pending)
                )
            # Both spellings are accepted so the scan is idempotent: the
            # tables carry string literals before the one-time --rewrite and
            # PMX_ macros after it, and --check has to work on either.
            for raw in STRING.findall(pending):
                spelling = raw.encode().decode("unicode_escape")
                names.setdefault(spelling, set()).add(guard)
            for ident in PMXREF.findall(pending):
                names.setdefault(demangle(ident), set()).add(guard)
            pending = None
    return names


def guard_of(guards):
    """The `#if` a member needs: any one of the tables that use it."""
    parts = sorted(guards)
    if len(parts) == 1:
        return parts[0]
    return " || ".join("(%s)" % p if "&&" in p else p for p in parts)


def render(names):
    idents = {}
    for spelling in names:
        ident = mangle(spelling)
        if ident in idents:
            raise SystemExit(
                "name mangling collides: %r and %r both give %s"
                % (idents[ident], spelling, ident)
            )
        idents[ident] = spelling

    ordered = sorted(names, key=lambda s: (mangle(s),))

    h = [BANNER]
    h.append("#ifndef PADMUX_NAMES_H")
    h.append("#define PADMUX_NAMES_H")
    h.append("")
    h.append("#include <stddef.h>")
    h.append("#include <stdint.h>")
    h.append("")
    h.append("struct padmux_names {")
    h.append("    /* Offset 0 is the empty string, which is what makes 0 usable")
    h.append("     * as the end of a row's function list. */")
    h.append("    char _none[1];")
    for spelling in ordered:
        h.append("#if %s" % guard_of(names[spelling]))
        h.append(
            '    char %s[sizeof "%s"];' % (mangle(spelling), spelling)
        )
        h.append("#endif")
    h.append("};")
    h.append("")
    h.append("extern const struct padmux_names padmux_names;")
    h.append("")
    h.append("/* The name a row's funcs[] entry stands for. */")
    h.append("static inline const char *padmux_name(uint16_t off) {")
    h.append("    return (const char *)&padmux_names + off;")
    h.append("}")
    h.append("")
    for spelling in ordered:
        ident = mangle(spelling)
        h.append("#if %s" % guard_of(names[spelling]))
        h.append(
            "#define PMX_%s ((uint16_t)offsetof(struct padmux_names, %s))"
            % (ident, ident)
        )
        h.append("#endif")
    h.append("")
    h.append("#endif /* PADMUX_NAMES_H */")
    h.append("")

    c = [BANNER]
    c.append('#include "padmux_names.h"')
    c.append("")
    c.append("const struct padmux_names padmux_names = {")
    c.append('    ._none = "",')
    for spelling in ordered:
        c.append("#if %s" % guard_of(names[spelling]))
        c.append('    .%s = "%s",' % (mangle(spelling), spelling))
        c.append("#endif")
    c.append("};")
    c.append("")

    return "\n".join(h), "\n".join(c)



def sub_name(m):
    """A `"NAME"` match -> `PMX_NAME`."""
    return "PMX_" + mangle(m.group(1).encode().decode("unicode_escape"))


def rewrite():
    """Turn the string literals in the MUXCTRL tables into PMX_ macros."""
    changed = []
    for rel, _, mode in SOURCES:
        path = os.path.join(ROOT, rel)
        out = []
        pending = None
        in_block = False

        if mode == "table":
            for line in open(path, encoding="utf-8"):
                # An #include's path is a string literal and is not a pad
                # name. Nothing else in these two files is a directive.
                peek, _ = code_of(line, in_block)
                fn = (lambda c: c) if peek.lstrip().startswith("#") else \
                    (lambda c: STRING.sub(sub_name, c))
                new_line, in_block = map_code(line, in_block, fn)
                out.append(new_line)
            text = "".join(out)
            if text != open(path, encoding="utf-8").read():
                open(path, "w", encoding="utf-8").write(text)
                changed.append(rel)
            continue

        for line in open(path, encoding="utf-8"):
            if MUXCTRL_OPEN.match(line):
                pending = line
            elif pending is not None:
                pending += line
            else:
                out.append(line)
                continue

            if pending.count("(") > pending.count(")"):
                continue

            out.append(STRING.sub(sub_name, pending))
            pending = None
        text = "".join(out)
        if text != open(path, encoding="utf-8").read():
            open(path, "w", encoding="utf-8").write(text)
            changed.append(rel)
    return changed


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="exit 1 when the generated files are stale")
    ap.add_argument("--rewrite", action="store_true",
                    help='convert "NAME" to PMX_NAME in the MUXCTRL tables')
    ap.add_argument("--selftest", action="store_true",
                    help="prove the mangling and the parser still hold")
    args = ap.parse_args()

    if args.selftest:
        return selftest()

    if args.rewrite:
        changed = rewrite()
        print("rewrote: %s" % (", ".join(changed) or "nothing to do"))
        # The names are the same either way, so fall through and regenerate.

    names = scan()
    h, c = render(names)
    wrote = []
    for rel, text in ((HEADER, h), (SOURCE, c)):
        path = os.path.join(ROOT, rel)
        old = open(path, encoding="utf-8").read() if os.path.exists(path) else None
        if old == text:
            continue
        if args.check:
            print("%s is stale -- run tools/gen_padmux_names.py" % rel,
                  file=sys.stderr)
            return 1
        open(path, "w", encoding="utf-8").write(text)
        wrote.append(rel)

    if args.check:
        print("padmux_names: up to date (%d names)" % len(names))
        return 0

    print("padmux_names: %d names, %d bytes of blob; wrote %s"
          % (len(names),
             1 + sum(len(n) + 1 for n in names),
             ", ".join(wrote) or "nothing (already current)"))
    return 0


def selftest():
    """The two things that would fail silently: mangling and continuation."""
    cases = [
        ("GPIO1_0", "GPIO1_0"),
        ("reserved", "reserved"),
        ("SDIO0_CCLK_OUT/EMMC_CLK_OUT", "SDIO0_CCLK_OUT__EMMC_CLK_OUT"),
        ("1WIRE", "_1WIRE"),
    ]
    for spelling, want in cases:
        got = mangle(spelling)
        assert got == want, "mangle(%r) = %r, wanted %r" % (spelling, got, want)

    # A wrapped MUXCTRL is one entry, not two, and its names all land in the
    # family the first line opened. This is the parser bug that would quietly
    # drop the names on continuation lines.
    names = scan()
    assert names, "scan() found no names at all"
    for spelling, guards in names.items():
        assert guards, "%r has no guard" % spelling
        assert all(g for g in guards)

    idents = {}
    for spelling in names:
        ident = mangle(spelling)
        assert ident not in idents, "collision on %s" % ident
        idents[ident] = spelling
        # What makes demangle() a function at all.
        assert "__" not in spelling, (
            "%r contains a double underscore, which mangle() also produces "
            "for a slash -- PMX_ identifiers stop round-tripping" % spelling
        )
        assert demangle(ident) == spelling, (
            "%r -> %s -> %r" % (spelling, ident, demangle(ident))
        )

    blob = 1 + sum(len(n) + 1 for n in names)
    assert blob < 65536, "blob %d bytes: a uint16_t offset no longer reaches" % blob

    print("gen_padmux_names selftest: %d names, %d-byte blob, all checks passed"
          % (len(names), blob))
    return 0


if __name__ == "__main__":
    sys.exit(main())
